### PR TITLE
Prevent edges from blinking while moving a node or while the diagram refresh

### LINKED ISSUE #966: Prevent diagrams from blinking after each refresh

### LINKED ISSUE #1065: Stop considering the source and target connection points as routing points

### LINKED ISSUE #1148: Adding or removing an edge may lead to unexpected layouts of other edges
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [ ] **I have specified my environment** : 
- Cloud

### Steps to reproduce

1. Create a `Robot Flow` model and a `Topography` diagram
2. Remove the edge between `Radar_Capture` and `Engine`

### Expected behavior

The edge is removed and any other edges should have been moved.

### Actual behavior

The edge is removed but the edge between `CPU` and `Motion_Engine` becomes straight (it has been rendered and layout again).

### PR DESCRIPTION
**Pull request by gcoutable**
### Type of this PR 

- [ ] Bug fix
- [x] New feature or improvement
- [ ] Documentation
- [ ] Cleanup
- [ ] Test
- [ ] Build/Releng

### Issue(s)

closes https://github.com/eclipse-sirius/sirius-components/issues/1130
closes #966
closes #1065
closes #1148 

### What does this PR do?

This PR overrides the default Sprotty edge router and the associated anchor computer to prevent the edge from blinking while the diagram is refreshed.
It handles straight edges between two elements and self-loop edges.
It also improves self-loop edges' position while moving the source/target element.

### Potential side effects

It reuses the backend edge layout algorithm. That means if the backend changes the way edges are layout, those changes will probably need to be reported in the frontend to prevent edges from blinking again.

### How to test this PR?

- [x] Manual Test : 
  - In a domain diagram, create some entities and create some edges.
  - Verify that the diagram refresh does not make edges blink.
  - Verify that moving an element used as a source/target of a self-loop edge does not make that self-loop edge blinking.

### CODE REVIEW

**Comment by sbegaudeau** [comment]
https://user-images.githubusercontent.com/422587/153388352-a3bc6c0b-bfa8-47da-b772-04e456a1cf11.mov

Things are quite weird on my side with this PR now. Could you rebase it (so without the Sprotty upgrade commit) and check that it still works for you.

**Comment by gcoutable** [comment]
> Enregistrement.de.l.ecran.2022-02-10.a.11.27.33.mov
> 
> Things are quite weird on my side with this PR now. Could you rebase it (so without the Sprotty upgrade commit) and check that it still works for you.

Could you try again?

**Comment by sbegaudeau** [comment]
https://user-images.githubusercontent.com/422587/155954473-483833c6-d79a-46db-ae81-6b5a8bfbdb52.mov

I tried once again this morning and the issue is still there. What did you change between the version I have tested on 2022/02/10 and the version that you have force pushed on 2022/02/18? From my understanding, you succeeded in reproducing my issue but it's not fixed.

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
It still does not work. As it stands today, I don't see this work being integrated in 2022.03.0

File: frontend/src/diagram/sprotty/routing/siriusPolylineEdgeRouter.ts [hunk 1]
```diff
@@ -0,0 +1,162 @@
...
+  SConnectableElement,
+  SParentElement,
+  SRoutableElement,
+  translatePoint,
+} from 'sprotty';
+import { Bounds, Point } from 'sprotty-protocol';
+import { isSiriusRectangleAnchor } from './siriusPolylineAnchor';
+
+export class SiriusPolylineEdgeRouter extends PolylineEdgeRouter {
+  refPosition(bounds: Bounds, ratio: Point): Point {
```
Comment (sbegaudeau) [inline frontend/src/diagram/sprotty/routing/siriusPolylineEdgeRouter.ts:26]: Use the type `Ratio` from `Diagram.types.ts` instead of `Point`

**Comment by sbegaudeau** [comment]
https://www.youtube.com/watch?v=PvWPB8AqlJ8

File: frontend/src/diagram/sprotty/routing/siriusPolylineEdgeRouter.ts (hunk 1 above)
Comment (gcoutable) [reply frontend/src/diagram/sprotty/routing/siriusPolylineEdgeRouter.ts:26]: Done

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
If the code to prevent edges from blinking is separated into two pull requests, it will not be reviewable. Could you merge [that PR](https://github.com/eclipse-sirius/sirius-components/pull/1066) into this one and add tests especially for the very sensitive parts of the algorithm such as the `siriusPolylineEdgeRouter` and the `siriusPolylineAnchor`. We know how fragile this code can be when modified.

**Comment by sbegaudeau** [comment]
You have updated this PR as recently as yesterday but as I explained in my previous comment on this very PR, it is not in a reviewable state. Edges are still blinking, you need to improve the organisation of the code that you are submitting.

**Comment by sbegaudeau** [comment]
Ok, with that first PR, things are not blinking anymore. I'll start reviewing the code but the behavior seems good.

**Comment by sbegaudeau** [comment]
The code of the first commit seems good, I'll test this one in isolation first to see its impact (on existing diagram for example).

File: doc/adrs/053_add_support_of_custom_anchors_on_frontend.adoc [hunk 2]
```diff
@@ -0,0 +1,29 @@
+= ADR-053 - Add support of custom anchors on frontend
+
+== Context
+
+Since https://github.com/eclipse-sirius/sirius-components/issues/565[#565] introducing custom anchors on the backend to support multiple edges between the same elements, we have diverged from Sprotty that use the center of the edge source element and edge target element as anchors to compute the edge route. That difference is one of the causes that makes edges blink when Sprotty renders the diagram, and that something we want to get rid of.
+
+== Decision
+
+We will support custom anchors on the frontend. We will leverage on anchors that has been computed by the backend. This behavior should come before we stop considering the source and target anchors as routing points presented in xref:054_stop_considering_the_source_and_target_anchors_as_routing_points_anymore.adoc[ADR-054].
```
Comment (sbegaudeau) [inline doc/adrs/053_add_support_of_custom_anchors_on_frontend.adoc:9]: Just say in ADR-54 (soon ADR-55), since we tend to move things (here rename ADR), this kind of links can be quite easily broken.

File: CHANGELOG.adoc [hunk 3]
```diff
@@ -30,6 +31,7 @@
 === Improvements
 
 - https://github.com/eclipse-sirius/sirius-components/issues/1165[#1165] [doc] Improve the pull request template
+- https://github.com/eclipse-sirius/sirius-components/issues/966[#966] [diagram] Add the support source and target edge position ratio on the frontend side. For further explanation see ADR-054.
```
Comment (sbegaudeau) [inline CHANGELOG.adoc:34]: ADR-55

File: frontend/src/diagram/sprotty/Diagram.types.ts [hunk 4]
```diff
@@ -11,6 +11,7 @@
  *     Obeo - initial API and implementation
  *******************************************************************************/
 
+import 'reflect-metadata';
```
Comment (sbegaudeau) [inline frontend/src/diagram/sprotty/Diagram.types.ts:14]: Do not import that here, that is a very special dependency already imported at a very special location (`index.ts`). If it's required by a test, import it in the test.

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

File: frontend/src/diagram/sprotty/Diagram.types.ts (hunk 4 above)
Comment (gcoutable) [reply frontend/src/diagram/sprotty/Diagram.types.ts:14]: Done

File: CHANGELOG.adoc (hunk 3 above)
Comment (gcoutable) [reply CHANGELOG.adoc:34]: Done

File: CHANGELOG.adoc [hunk 5]
```diff
@@ -15,6 +15,7 @@
 === Breaking changes
 
 - https://github.com/eclipse-sirius/sirius-components/issues/1088[#1088] [core] Change the type of `IRepresentationDescription#id` from UUID to String. This will allow us, when we will receive an operation to perform with a given representation description identifier, to determine if this operation should be handled by the Sirius Desktop compatibility layer, the View support or by a programmatic API
+- https://github.com/eclipse-sirius/sirius-components/issues/966[#966] [core] The source and target edge anchor are not considered as routing points anymore. Edges of old diagrams may have unexpected behavior since new edges will have two less routing points than existing edges in old diagrams. For further explanation see ADR-053.
```
[the remark this answers is not in the document]
Comment (gcoutable) [reply CHANGELOG.adoc:18]: Done

File: doc/adrs/054_stop_considering_the_source_and_target_anchors_as_routing_points_anymore.adoc [hunk 6]
```diff
@@ -0,0 +1,31 @@
...
+Since this should come after we have customized the sprotty edge router to take account of our edge anchors, we will have to adapt that customization.
+
+== Status
+
+Done
+
+== Consequences
+
+- Source and target anchors will be updated according to the ELK layout after the user has used the `Arrange all`.
+- This ADR invalidates xref:017_improve_edge_source_and_target_anchors.adoc[ADR 017 Improve edge source and target anchors]
```
[the remark this answers is not in the document]
Comment (gcoutable) [reply doc/adrs/054_stop_considering_the_source_and_target_anchors_as_routing_points_anymore.adoc:31]: Done

File: doc/adrs/053_add_support_of_custom_anchors_on_frontend.adoc (hunk 2 above)
Comment (gcoutable) [reply doc/adrs/053_add_support_of_custom_anchors_on_frontend.adoc:9]: Done

File: doc/adrs/053_add_support_of_custom_anchors_on_frontend.adoc [hunk 7]
```diff
@@ -0,0 +1,29 @@
+= ADR-053 - Add support of custom anchors on frontend
```
[the remark this answers is not in the document]
Comment (gcoutable) [reply doc/adrs/053_add_support_of_custom_anchors_on_frontend.adoc:1]: Done

File: frontend/src/diagram/sprotty/siriusMove.ts [hunk 8]
```diff
@@ -33,37 +42,40 @@ export class SiriusMoveCommand extends MoveCommand {
...
+        edge.routingPoints = routedPoints.slice(1, -1);
+      }
+      this.resetLabelPosition(edge, routedPoints);
     });
   }
 
-  private resetLabelPosition(edge: SEdge) {
-    if (edge.routingPoints?.length === 2) {
+  private resetLabelPosition(edge: SEdge, routedPoints: RoutedPoint[]) {
+    if (routedPoints?.length === 2) {
```
[the remark this answers is not in the document]
Comment (gcoutable) [reply frontend/src/diagram/sprotty/siriusMove.ts:55]: Done

File: doc/adrs/055_stop_considering_the_source_and_target_anchors_as_routing_points_anymore.adoc [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+The new behavior will come with https://github.com/eclipse-sirius/sirius-components/issues/1065[#1065].
+This new behavior should come after the implementation of a custom router discussed in ADR-054.
+
+=== Backend
+
+We will keep the `EdgeRoutingPointsProvider` to handle self-loop edges.
+We will move the edge label position algorithm from the `EdgeRoutingPointsProvider` to `EdgeLabelPositionProvider`.
+Since we introduced edge anchor positions we will adapt the `ELKLayoutedDiagramProvider` to compute anchor position instead of the source and target routing points. 
+
+image:054_anchors_inferred_from_ELK.png[alt]
```
Comment (sbegaudeau) [inline doc/adrs/055_stop_considering_the_source_and_target_anchors_as_routing_points_anymore.adoc:23]: 055 (I'll fix it)

**Review by sbegaudeau — APPROVED** [review]
