### PR TITLE
[5808] Refactor index lifecycle to support multiple editing contexts

### LINKED ISSUE #5808: Indexing doesn't work properly for projects with multiple editing contexts
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- All

We index data per project in Elasticsearch: each project has its own index containing documents related to this project.
When we index an editing context, we first clear the index, then we index the content of the editing context.
As a result, we clear data from all the editing contexts, but we only re-index the data from one.

### PR DESCRIPTION
**Pull request by gdaniel**
# Pull request template

Fixes #5808 
Based on #5807 

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

**Comment by gdaniel** [comment]
This PR provides extension mechanisms to create/delete/update indices.
Default implementations for these feature are provided, and fix the issue in #5808.

The main reason to provide all these extension mechanism is to give as much freedom as possible to downstream applications, specifically:
- To create index with the appropriate configuration (relevant mappings for their metamodels, relevant settings, etc), and to allow to create multiple indices for a single editing context if needed.
- To delete custom indexes
- To update index content with relevant information not provided by the default implementation. For example, some applications attach information to semantic objects that is not visible when traversing the resource, but still needs to be indexed.

File: packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexInitializer.java [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+        this.indexCreationService = Objects.requireNonNull(indexCreationService);
+        this.indexUpdateService = Objects.requireNonNull(indexUpdateService);
+        this.optionalElasticSearchClient = Objects.requireNonNull(optionalElasticSearchClient);
+    }
+
+    @Async
+    @Override
+    public void run(String... args) throws Exception {
+        this.optionalElasticSearchClient.ifPresent(elasticSearchClient -> {
+            Window<Project> projects = this.projectSearchService.findAll(ScrollPosition.keyset(), Integer.MAX_VALUE - 1, Map.of());
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexInitializer.java:76]: For the moment we only index the project's semantic data on startup. I don't know if it is good enough or if we want to index the library contents too.
Anyways, we may consider updating `SemanticDataSearchService` with a `findAll` method.

File: packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexInitializer.java [hunk 2]
```diff
@@ -0,0 +1,87 @@
...
+            for (Project project : projects) {
+                List<ProjectSemanticData> allProjectSemanticData = this.projectSemanticDataSearchService.findAllByProjectId(AggregateReference.to(project.getId()));
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexInitializer.java:78]: Note that I also removed the piece of code responsible for deleting dangling indices.
Since we now allow to extend the default behavior to create/delete indices (potentially creating multiple indices for a single editing context), it wasn't easy to have a generic solution to delete dangling indices.

In the end, the only way to create dangling indices is to manually delete semantic data from the database (deleting semantic data from the UI should fire the event the triggers the deletion of the index). I don't think it is a big issue for the moment, but if needed I can work on a solution.

File: packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexLifecycleManager.java [hunk 3]
```diff
@@ -0,0 +1,101 @@
...
+        this.editingContextSearchService = Objects.requireNonNull(editingContextSearchService);
+        this.projectSemanticDataSearchService = Objects.requireNonNull(projectSemanticDataSearchService);
+        this.indexCreationService = Objects.requireNonNull(indexCreationService);
+        this.indexDeletionService = Objects.requireNonNull(indexDeletionService);
+        this.indexUpdateService = Objects.requireNonNull(indexUpdateService);
+    }
+
+    @Async
+    @TransactionalEventListener
+    public void onProjectDeletedEvent(ProjectDeletedEvent projectDeletedEvent) {
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexLifecycleManager.java:70]: There is no `SemanticDataDeletedEvent`, so I used this one, but I am wondering if we should add the event instead of relying on a project event here.

File: packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexQueryService.java [hunk 4]
```diff
@@ -58,7 +58,7 @@ public List<IIndexEntry> search(String query) {
             ElasticsearchClient elasticSearchClient = this.optionalElasticSearchClient.get();
             try {
                 SearchResponse<IIndexEntry> response = elasticSearchClient.search(searchRequest -> searchRequest
-                        .index(ProjectIndexLifecycleManager.PROJECT_INDEX_NAME_PREFIX + "*")
+                        .index("*")
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexQueryService.java:61]: Now that we allow to customize how indices are created, we want to search everywhere, not only in indices with a given prefix.
In practice this doesn't change anything for the default implementation (assuming everything in Elasticsearch is related to Sirius Web).

**Comment by gdaniel** [comment]
I didn't really know how to add tests for this PR, because the only feature in Sirius Web we can use to check if the indices work as expected is the search command, which was already tested in the previous PR.
Let me know if you want some additional tests.

File: packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/api/IDefaultIndexCreationService.java [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+package org.eclipse.sirius.web.infrastructure.elasticsearch.services.api;
+
+/**
+ * The default implementation that creates the index for an editing context.
+ *
+ * @author gdaniel
+ */
+public interface IDefaultIndexCreationService {
+
+    boolean createIndex(String editingContextId);
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/api/IDefaultIndexCreationService.java:22]: boolean? That's an odd return type for the creation.

File: packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexInitializer.java (hunk 1 above)
Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexInitializer.java:76]: - This should be transactional
- I don't need a paginated API for this :)

File: packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexLifecycleManager.java (hunk 3 above)
Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/elasticsearch/services/IndexLifecycleManager.java:70]: - Yes we should be you can't do it for now
- This should also be transactionnal

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
I"ll update some minor details and merge it after

**Review by sbegaudeau — APPROVED** [review]
I'll wait for the build and merge it
