### PR TITLE
[5200] Add support for uploading projects with models referencing each other

### LINKED ISSUE #5200: Cannot upload a project with a model referencing another
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- 2025.6.9
* [x] **I have specified my environment** : 
- All

### Steps to reproduce

1) Create a project with two models.
2) In the first model (modelA), reference an element from the second model (modelB)
3) Download the project
4) Upload the project

### Expected behavior

The project upload without any error

### Actual behavior

The project upload with an error: "The resource XXXXX contains unresolvable proxies and will not be uploaded."
This error comes from `DocumentSanitizedJsonContentProvider`.
It is due to the fact that if the first model (modelA) to be upload is the one containing references to the second model (modelB) then it will contain proxies.

### PR DESCRIPTION
**Pull request by pcdavid**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/5200
Signed-off-by: Pierre-Charles David <pierre-charles.david@obeo.fr>

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/dto/UploadDocumentInput.java [hunk 1]
```diff
@@ -24,5 +24,8 @@
  *
  * @author hmarchadour
  */
-public record UploadDocumentInput(@NotNull UUID id, @NotNull String editingContextId, @NotNull UploadFile file, boolean readOnly) implements IInput {
+public record UploadDocumentInput(@NotNull UUID id, @NotNull String editingContextId, @NotNull UploadFile file, boolean allowProxies, boolean readOnly) implements IInput {
+    public UploadDocumentInput(@NotNull UUID id, @NotNull String editingContextId, @NotNull UploadFile file, boolean readOnly) {
+        this(id, editingContextId, file, false, readOnly);
+    }
 }
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/dto/UploadDocumentInput.java]: This is mainly used to communicate between the frontend and backend. It would be very odd to use it to carry strictly internal data hidden from the GraphQL schema. I'll have to retrieve the code and look at it in more details to understand the flow of the code.

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/dto/UploadDocumentInput.java (hunk 1 above)
Comment (pcdavid) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/document/dto/UploadDocumentInput.java]: Indeed, it's no longer needed and I forgot to clean it up after rebasing the PR.

It was needed in my initial version, before #5446 rewrote the project import logic: [in the old version](https://github.com/eclipse-sirius/sirius-web/blob/v2025.10.0/packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectImporter.java#L185), `ProjectImporter` used to import the documents by programmatically creating and sending `UploadDocumentInput` to the editingContextEventProcessor.

**Review by sbegaudeau — APPROVED** [review]
Everything I tried seems to work nicely :+1:
