### PR TITLE
[5002] Retrieve context menu entries in tree representations dynamically

### LINKED ISSUE #5002: Imported studio libraries should be read-only but can be modified
## Steps to reproduce

1. Create a studio with some content
2. Publish it as a studio library L
3. Create a new, empty studio
4. Import L. Make sure to *import* it and not copy it.
5. The contents of L is available in the new studio.
6. It should be read-only, but elements can be edited, added or removed: rename a representation description, add a new node description etc.

It seems elements can not be *deleted*, but it's not enough.

### PR DESCRIPTION
**Pull request by sbegaudeau**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/5002
Signed-off-by: Stéphane Bégaudeau <stephane.begaudeau@obeo.fr>

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/DomainViewTreeDescriptionProvider.java [hunk 1]
```diff
@@ -299,7 +299,7 @@ private List<TreeItemContextMenuEntry> getContextMenuEntries() {
                 .build();
 
         var expandAllMenuEntry = new TreeBuilders().newCustomTreeItemContextMenuEntry()
-                .contributionId("expandAll")
+                .contributionId("expand-all")
```
Comment (pcdavid) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/DomainViewTreeDescriptionProvider.java]: Should refer to `ExplorerTreeItemContextMenuEntryProvider.EXPAND_ALL`.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerTreeItemContextMenuEntryProvider.java [hunk 2]
```diff
@@ -64,41 +89,90 @@ public boolean canHandle(IEditingContext editingContext, TreeDescription treeDes
...
+    private List<ITreeItemContextMenuEntry> getDocumentContextMenuEntries(IEMFEditingContext editingContext, TreeItem treeItem) {
+        var optionalResource = this.objectSearchService.getObject(editingContext, treeItem.getId())
+                .filter(Resource.class::isInstance)
+                .map(Resource.class::cast);
+        if (optionalResource.isPresent()) {
+            var resource = optionalResource.get();
+
+            List<ITreeItemContextMenuEntry> entries = new ArrayList<>();
+            if (!this.readOnlyObjectPredicate.test(resource)) {
+                entries.add(new SingleClickTreeItemContextMenuEntry(NEW_ROOT_OBJECT, "", List.of(), false));
```
Comment (pcdavid) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerTreeItemContextMenuEntryProvider.java:113]: Is this expected that the actual labels and icons provided here are empty and instead still provided solely by the frontend (e.g. in DownloadDocumentTreeItemContextMenuContribution)?

**Review by pcdavid — CHANGES_REQUESTED** [review]
Not sure if that was supposed to be in the scope of this PR, but playing the original scenario from #5002, once I have imported all the studio library components, I can edit the name & value of the colors (imported in the "shared_components" document) from the _Details_ view.

The change does not seem to be actually persisted (a cold reload of the project shows the original names & values).

Image

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerTreeItemContextMenuEntryProvider.java (hunk 2 above)
Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/ExplorerTreeItemContextMenuEntryProvider.java:113]: Yes, we did it the same way for other entries in the past

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/DomainViewTreeDescriptionProvider.java (hunk 1 above)
Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/representations/DomainViewTreeDescriptionProvider.java]: Done

**Review by pcdavid — APPROVED** [review]
