### PR TITLE
[4214] Rework selection in the Explorer view

### LINKED ISSUE #4059: Collapsible element re-expands when child element is selected
When a collapsible element is collapsed and a child element is selected, the parent element automatically re-expands. This occurs because we automatically expands elements in the tree structure to ensure the selected element is visible. However, this behavior can be undesirable when the parent element is not selectable, as it causes the parent to re-expand unnecessarily.

### Expected behavior

The parent element should remain collapsed, even if a child element is selected.

### Actual behavior

model-browser-reveal-selected

Possible solution:

One possible solution to this issue is to clear the selection when a non-selectable element is clicked, such as when collapsing a parent element. This would prevent the parent element from re-expanding unnecessarily."

### LINKED ISSUE #4214: Replace "Synchronize with representation" mode with a simpler "Reveal selection" action
The "Synchronize with representation" behavior:

* has non-obvious semantics which make it confusing to end-users (even when disabled, _some kind_ of selection synchronization still happens, just only on the currently visible items);
* has historically been the cause of several (sometimes subtle) bugs and regressions;
* has a non-obvious UI (to me at least), with a plain (non-toggle) button being "normal" when the mode is active, but appearing as _disabled_ when inactive, which looks like an action that can not be performed;
* has performance impacts when enabled: for (almost?) all selection changes, at least one query to the backend to know the path of all the selected elements, and possibly one computation of a new tree subscription with a configuration set to expand all the required nodes.

Proposal:
* keep the "if an element selected e.g. in a diagram is currently visible in the explorer, mark the corresponding item as selected" behavior (what we have when the "Synchronize" mode is disabled);
* replace the "mode" with a single-shot action button modeled after the "Select opened file" action in IntelliJ: when the action is invoked, ensure all the selected elements are _visible_ in the Explorer (this may require expanding sub-trees) and then mark them selected as above.

image

### PR DESCRIPTION
**Pull request by pcdavid**
- **[4214] Remove the synchronizedWithSelection mode from the Explorer**
- **[4214] Add explicit Explorer action to reveal the selected items**
- **[4214] Replace "Synchronize with representation" mode with a simpler "Reveal selection" action**

**This still needs tests**, but I've pushed it to get feedback on the new behavior.

The selected (highlighted) state of visible items is still synchronized with the workbench selection, but the explorer no longer tries to keep all items corresponding to selected items visible by expanding the corresponding tree path.
This now only happens on an explicit user action using the new button.

https://github.com/user-attachments/assets/ba731eb6-537e-4d45-a438-9aed08974fd5

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/trees/frontend/sirius-components-trees/src/toolbar/TreeToolBar.tsx [hunk 1]
```diff
@@ -36,19 +38,33 @@ const useTreeToolbarStyles = makeStyles()((theme) => ({
...
+      if (labels.length > maxLabelsToShow) {
+        setSelectElementsLabel(
+          `Select ${labels.slice(0, maxLabelsToShow).join(', ')} (and ${labels.length - maxLabelsToShow} more)`
+        );
+      } else {
+        setSelectElementsLabel(`Select ${labels.join(', ')}`);
+      }
+    }
+  }, [objectLabelsLoading, labels]);
+  const { selection } = useSelection();
```
Comment (sbegaudeau) [inline packages/trees/frontend/sirius-components-trees/src/toolbar/TreeToolBar.tsx]: This entire concern can be extracted along with the button. All the concerns from all the actions in this toolbar do not need to be performed by the toolbar itself. I also don't think you need that many states (one for the objects and one for the labels)

File: packages/core/frontend/sirius-components-core/src/objectslabels/useObjectsLabels.ts [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+    if (error) {
+      addErrorMessage(error.message);
+    }
+  }, [error]);
+
+  useEffect(() => {
+    if (!loading && data) {
+      setLabels(data.viewer.editingContext.objects.map((obj) => obj.label));
+    }
+  }, [loading, data]);
```
Comment (sbegaudeau) [inline packages/core/frontend/sirius-components-core/src/objectslabels/useObjectsLabels.ts]: Why do you need a state? You can just return that, see `useInvokeImpactAnalysis` for example

File: packages/core/frontend/sirius-components-core/src/objectslabels/useObjectsLabels.ts [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+
+  const fetchObjectLabels = useCallback(
+    (editingContextId: string, objectIds: string[]) => {
+      loadLabels({ variables: { editingContextId, objectIds } });
+    },
+    [loadLabels]
+  );
```
Comment (sbegaudeau) [inline packages/core/frontend/sirius-components-core/src/objectslabels/useObjectsLabels.ts]: I don't think you need a useCallback either

File: packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/handlers/EditingContextObjectsEventHandler.java [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+        List<Object> result = new ArrayList<>();
+        if (input instanceof EditingContextObjectsInput objectsInput) {
+            for (var objectId : objectsInput.objectIds()) {
+                Optional<Object> optionalObject = this.objectSearchService.getObject(editingContext, objectId);
+                if (optionalObject.isEmpty() && editingContext instanceof IEMFEditingContext emfEditingContext) {
+                    optionalObject = emfEditingContext.getDomain().getResourceSet().getResources().stream()
+                            .filter(resource -> resource.getURI().toString().contains(objectId))
+                            .map(Object.class::cast)
+                            .findFirst();
+                }
```
Comment (sbegaudeau) [inline packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/handlers/EditingContextObjectsEventHandler.java]: I see that you can copied/paste that from `EditingContextObjectEventHandler` but we should not have done that there, it should be done by the `IObjectSearchService`. I'll look into this first.

Comment (sbegaudeau) [reply packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/handlers/EditingContextObjectsEventHandler.java]: I have sent a PR to fix that globally and I'll update this small part when I'll rebase it

File: packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/ExplorerView.tsx [hunk 5]
```diff
@@ -168,23 +175,26 @@ export const ExplorerView = forwardRef<WorkbenchViewHandle, WorkbenchViewCompone
...
 
-    // If we should auto-expand to reveal the selection, we need to compute the tree path to expand
     const selectionKey: string = selection?.entries
       .map((entry) => entry.id)
       .sort()
       .join(':');
-    useEffect(() => {
-      if (state.synchronizedWithSelection && state.tree) {
+
+    const revealSelection = useCallback(() => {
```
Comment (sbegaudeau) [inline packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/workbench-views/explorer/ExplorerView.tsx:188]: I don't think you need to use `useCallback` as much as you do, did it really create an issue not to?

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
In terms of behavior, I think it's a great improvement. I'll look into the minor details I've mentioned here and merge it directly since it shouldn't take long.

**Review by sbegaudeau — APPROVED** [review]
I'll merge it after the build :+1:
