### PR TITLE
[5599] Fix project download always downloading default semantic data

### LINKED ISSUE #5599: Fix project download always downloading default ('main') semantic data
* [X] **I have checked that this bug has not yet been reported by someone else**
* [X] **I have checked that this bug appears on Chrome**
* [X] **I have specified the version** :
- latest

### Expected behavior

It should be possible to download a project's specific semantic data.

### Actual behavior

Currently downloading a project always downloads its default ('main') semantic data.

### PR DESCRIPTION
**Pull request by adaussy**
…tic data

Bug: https://github.com/eclipse-sirius/sirius-web/issues/5599

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectSemanticDataExportParticipant.java [hunk 1]
```diff
@@ -72,25 +72,25 @@ public ProjectSemanticDataExportParticipant(IIdentityService identityService, IE
...
 
-        var optionalEditingContext = this.projectSemanticDataSearchService.findByProjectId(AggregateReference.to(project.getId()))
-                .map(ProjectSemanticData::getSemanticData)
-                .map(AggregateReference::getId)
-                .map(UUID::toString)
-                .flatMap(editingContextSearchService::findById)
-                .filter(IEMFEditingContext.class::isInstance)
-                .map(IEMFEditingContext.class::cast);
+        var optionalEditingContext = this.projectSemanticDataSearchService.findBySemanticDataId(AggregateReference.to(UUID.fromString(editingContextId)))
+            .map(ProjectSemanticData::getSemanticData)
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectSemanticDataExportParticipant.java]: Let's say someone give your the id of a project A and the editingContextId of a project B, they can retrieve data from both sources. This is exactly the kind of way one could use to retrieve data from a project they do not have access to.

Here you are also considering that you know that the editing context id is a UUID, which is not always the case and you are parsing it without the appropriate class. I specifically asked for `name` as a parameter and for the backend to look by the project semantic data name in order to ensure that we couldn't export inconsistent data.

Please follow the pieces of advice that you ask me for.

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/ProjectDownloadController.java [hunk 2]
```diff
@@ -54,23 +55,41 @@ public class ProjectDownloadController {
...
     @ResponseBody
     @GetMapping(path = "/{projectId}")
     public ResponseEntity<Resource> downloadProject(@PathVariable String projectId) {
+        return projectEditingContextService.getEditingContextId(projectId)
+                .map(editingContext -> doDownloadProject(projectId, editingContext))
+                .orElse(new ResponseEntity<>(null, new HttpHeaders(), HttpStatus.NOT_FOUND));
+    }
+
+    @ResponseBody
+    @GetMapping(path = "/{projectId}/editing-context-name/{editingContextName}")
```
Comment (adaussy) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/controllers/ProjectDownloadController.java]: I was not sure about the "editing-context-name" parameter. Maybe should prefer to simply keep name here but I was affraid that would create confusion with the project name.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectSemanticDataExportParticipant.java (hunk 1 above)
Comment (adaussy) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectSemanticDataExportParticipant.java]: Done.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/api/IProjectExportService.java [hunk 3]
```diff
@@ -20,5 +20,16 @@
...
 public interface IProjectExportService {
-    byte[] export(Project project);
+
+    /**
+     * Exports the project to a binary format.
+     *
+     * @param project
+     *         The project
+     * @param editingContext
+     *         The editing context id to export
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/api/IProjectExportService.java]: `editingContextId` if it's the id

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectExportService.java [hunk 4]
```diff
@@ -53,13 +53,13 @@ public ProjectExportService(List<IProjectExportParticipant> projectExportPartici
 
     @Override
     @Transactional(readOnly = true)
-    public byte[] export(Project project) {
+    public byte[] export(Project project, String editingContext) {
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/ProjectExportService.java]: `editingContextId`

File: packages/sirius-web/backend/sirius-web-tests-data/src/main/resources/sirius-web-scripts/multi-editing-context-project.sql [hunk 5]
```diff
@@ -0,0 +1,323 @@
...
+  'Topography',
+  'siriusComponents://representation?type=Diagram',
+  '2025-10-07 13:41:41.494685+00',
+  '2025-10-07 13:41:41.494685+00',
+  '',
+  '3f155db4-6771-459a-9fec-6a3a77238d31'
+);
+
+-- Exporting table: public.representation_content
+INSERT INTO public.representation_content (
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-tests-data/src/main/resources/sirius-web-scripts/multi-editing-context-project.sql]: Please ensure that your files is formatted properly, that's unreadable

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectDownloadControllerIntegrationTests.java [hunk 6]
```diff
@@ -148,6 +149,48 @@ public void givenStudioWhenTheDownloadOfProjectIsRequestedThenTheSemanticDataAre
         }
     }
 
+    @Test
+    @GivenSiriusWebServer
+    @DisplayName("Given a Flow project with more than one editing context, when the download of the project is requested with a specific editing context id, then the correct semantic data are " +
+            "retrieved")
+    public void givenMultiContextFlowProjectWhenTheDownloadOfProjectIsRequestedThenTheSemanticDataAreRetrieved() {
+        this.givenCommittedTransaction.commit();
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/projects/ProjectDownloadControllerIntegrationTests.java]: This should not be necessary nowadays

File: packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/navbar/context-menu/DownloadProjectMenuItem.tsx [hunk 7]
```diff
@@ -19,16 +19,14 @@ import MenuItem from '@mui/material/MenuItem';
 import { useContext } from 'react';
 import { DownloadProjectMenuItemProps } from './DownloadProjectMenuItem.types';
 
-export const DownloadProjectMenuItem = ({ project, onClick }: DownloadProjectMenuItemProps) => {
+export const DownloadProjectMenuItem = ({ project, name, onClick }: DownloadProjectMenuItemProps) => {
   const { httpOrigin } = useContext<ServerContextValue>(ServerContext);
 
+  var href = name
+    ? `${httpOrigin}/api/projects/${project.id}/editing-context-name/${name}`
```
Comment (sbegaudeau) [inline packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/navbar/context-menu/DownloadProjectMenuItem.tsx]: I'll use `?name=` instead

File: packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx [hunk 8]
```diff
@@ -137,7 +137,7 @@ export const EditProjectView = () => {
     const initialSelection: Selection = { entries };
 
     content = (
-      <ProjectContext.Provider value={{ project: state.project }}>
+      <ProjectContext.Provider value={{ project: state.project, name: name }}>
```
Comment (sbegaudeau) [inline packages/sirius-web/frontend/sirius-web-application/src/views/edit-project/EditProjectView.tsx]: `name` only works too

**Review by sbegaudeau — APPROVED** [review]
I'll merge it after the build
