### PR TITLE
[6267] Allow customizing the content of the Views Explorer via delegates

### LINKED ISSUE #6267: Add the ability to customize how representations are grouped in the Views Explorer view

### LINKED ISSUE #6268: Improve isDeletable and isEditable of the Views Explorer view to check readonly
* [ ] **I have checked that this bug has not yet been reported by someone else**
* [ ] **I have checked that this bug appears on Chrome**
* [ ] **I have specified the version** :
- latest
- other: please specify
* [ ] **I have specified my environment** : 
- All
- my computer: Windows? Linux? Cloud?
- Cloud

### Screenshots

...

### Steps to reproduce

...

### Expected behavior

...

### Actual behavior

...

### PR DESCRIPTION
**Pull request by theogiraudet**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/6267
Bug: https://github.com/eclipse-sirius/sirius-web/issues/6268

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

**Comment by theogiraudet** [comment]
I improved the "children provider" parts to implement the delegate pattern we already use at some place in the codebase.

**Comment by theogiraudet** [comment]
Go back to draft, since this modification can have some unwanted behaviors.
For instance `ViewsExplorerTreeDescriptionProvider#getLabel` must be configurable too.
Should the synthetic tree be more agnostic of `IRepresentationDescription` and/or should we set the label directly in the `RepresentationDescriptionType`/`RepresentationKind` type?

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/viewsexplorer/services/ViewsExplorerTreeDescriptionProvider.java [hunk 1]
```diff
@@ -230,17 +202,7 @@ private IStatus getRenameHandler(VariableManager variableManager, String newLabe
...
-
-            var optionalHandler = this.renameTreeItemHandlers.stream()
-                    .filter(handler -> handler.canHandle(editingContext, treeItem, newLabel))
-                    .findFirst();
-
-            if (optionalHandler.isPresent()) {
-                IRenameTreeItemHandler renameTreeItemHandler = optionalHandler.get();
-                return renameTreeItemHandler.handle(editingContext, treeItem, newLabel, optionalTree.get());
-            }
+            return this.viewsExplorerLabelService.editLabel(newLabel, optionalEditingContext.get(), optionalTree.get(), optionalTreeItem.get());
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/viewsexplorer/services/ViewsExplorerTreeDescriptionProvider.java]: The editing context should be the first parameter

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/viewsexplorer/services/api/IViewsExplorerDeleteService.java [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+import org.eclipse.sirius.components.representations.IStatus;
+import org.eclipse.sirius.components.trees.Tree;
+import org.eclipse.sirius.components.trees.TreeItem;
+
+/**
+ * Used to delete elements in the views explorer.
+ *
+ * @author tgiraudet
+ */
+public interface IViewsExplorerDeleteService {
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/viewsexplorer/services/api/IViewsExplorerDeleteService.java]: `IViewsExplorerDeletionService` to match the naming conventions of other services

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/viewsexplorer/services/ComposedViewsExplorerContentService.java [hunk 3]
```diff
@@ -0,0 +1,68 @@
...
+        this.defaultViewsExplorerContentService = Objects.requireNonNull(defaultViewsExplorerContentService);
+        this.representationMetadataSearchService = Objects.requireNonNull(representationMetadataSearchService);
+        this.representationDescriptionSearchService = Objects.requireNonNull(representationDescriptionSearchService);
+    }
+
+    public List<RepresentationKind> getContents(IEditingContext editingContext) {
+        return new UUIDParser().parse(editingContext.getId())
+                .map(semanticDataId -> {
+                    var allMetadata = this.representationMetadataSearchService.findAllRepresentationMetadataBySemanticData(AggregateReference.to(semanticDataId));
+                    var allDescriptions = this.representationDescriptionSearchService.findAll(editingContext);
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/viewsexplorer/services/ComposedViewsExplorerContentService.java:58]: This logic should either be outside or in the default behavior

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/viewsexplorer/services/ComposedViewsExplorerContentService.java [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+                    return this.viewsExplorerContentServiceDelegates
+                        .stream()
+                        .filter(delegate -> delegate.canHandle(editingContext))
+                        .findFirst()
+                        .map(delegate -> delegate.getContents(allMetadata, allDescriptions))
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/viewsexplorer/services/ComposedViewsExplorerContentService.java]: It's odd not to have the editing context here

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
I'll update the PR and ensure that it gets merged

**Review by sbegaudeau — APPROVED** [review]
I'll merge it after the build
