### PR TITLE
[5953] Provide AdapterFactory Descriptors instead of AdapterFactories

### LINKED ISSUE #5953: Provide AdapterFactory Descriptors instead of AdapterFactories
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior

`AdapterFactories` are currently declared as `@Bean`.
So there is one instance of each declared `AdapterFactory`.

When a project is disposed the `AdapterFactory` retains an `ItemProvider` on each element of this project, so the `Resources` of the project are not disposed.

It causes Sirius Web application to crash after some times, because of a lot of `Resources` not disposed.

The goal is to provide `AdapterFactory.Descriptor` as `@Bean` instead of `AdapterFactories`.
Then, `ComposedAdapterFactory` will be instantiated (from all declared `AdapterFactory.Descriptors`) and disposed each time it is needed in the codebase.

### PR DESCRIPTION
**Pull request by AxelRICHARD**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/5953

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [x] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/configuration/EMFConfiguration.java [hunk 1]
```diff
@@ -62,11 +62,23 @@ public void initializeChildExtenders() {
...
-        composedAdapterFactory.addAdapterFactory(new ReflectiveItemProviderAdapterFactory());
-        return composedAdapterFactory;
+    public ComposedAdapterFactory.Descriptor ecoreAdapterFactoryDescriptor() {
+        return new ComposedAdapterFactory.Descriptor() {
+            @Override
+            public AdapterFactory createAdapterFactory() {
+                return new EcoreAdapterFactory();
+            }
+        };
+    }
```
Comment (pcdavid) [inline packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/configuration/EMFConfiguration.java:66]: I think it can simply `return EcoreAdapterFactory::new;`

File: packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/configuration/EMFConfiguration.java [hunk 2]
```diff
@@ -62,11 +62,23 @@ public void initializeChildExtenders() {
...
+
+    @Bean
+    public ComposedAdapterFactory.Descriptor reflectiveItemProviderAdapterFactoryDescriptor() {
+        return new ComposedAdapterFactory.Descriptor() {
+            @Override
+            public AdapterFactory createAdapterFactory() {
+                return new ReflectiveItemProviderAdapterFactory();
+            }
+        };
```
Comment (pcdavid) [inline packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/configuration/EMFConfiguration.java]: Same remark.

File: packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultEMFLabelService.java [hunk 3]
```diff
@@ -67,7 +69,12 @@ public StyledString getStyledLabel(EObject self) {
     public List<String> getImagePaths(EObject self) {
         List<String> result = List.of("/icons/svg/Default.svg");
 
-        Adapter adapter = this.composedAdapterFactory.adapt(self, IItemLabelProvider.class);
+        var adapterFactories = new ArrayList<>();
+        for (Descriptor composedAdapterFactoryDescriptor : this.composedAdapterFactoryDescriptors) {
+            adapterFactories.add(composedAdapterFactoryDescriptor.createAdapterFactory());
+        }
```
Comment (pcdavid) [inline packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultEMFLabelService.java]: Could we just `self.eResource().getResourceSet().getAdapterFactories()` here instead of re-creating a new `ComposedAdapterFactory` for every `getImagePath` call? Not tested.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultContentService.java [hunk 4]
```diff
@@ -32,21 +34,28 @@
...
     public List<Object> getContents(Object object) {
         List<Object> contents = new ArrayList<>();
         if (object instanceof EObject eObject) {
-            Adapter adapter = this.composedAdapterFactory.adapt(eObject, IEditingDomainItemProvider.class);
+            var adapterFactories = new ArrayList<>();
+            for (Descriptor composedAdapterFactoryDescriptor : this.composedAdapterFactoryDescriptors) {
+                adapterFactories.add(composedAdapterFactoryDescriptor.createAdapterFactory());
+            }
+            var composedAdapterFactory = new ComposedAdapterFactory(adapterFactories.toArray(AdapterFactory[]::new));
+            Adapter adapter = composedAdapterFactory.adapt(eObject, IEditingDomainItemProvider.class);
```
Comment (pcdavid) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultContentService.java]: Same remark as above: if possible, use `eObject.eResource().getResourceSet().getAdapterFactories()` instead of creating a new ComposedAdapterFactory on every `getContent()` call.

File: CHANGELOG.adoc [hunk 5]
```diff
@@ -55,7 +55,27 @@ On the frontend, the `ProjectTemplateCard` component has been removed; the `NewP
...
+```
+@Bean
+public ComposedAdapterFactory.Descriptor papayaAdapterFactoryDescriptor() {
+    return new ComposedAdapterFactory.Descriptor() {
+        @Override
+        public AdapterFactory createAdapterFactory() {
+            return new PapayaItemProviderAdapterFactory();
+        }
+    };
+}
```
Comment (pcdavid) [inline CHANGELOG.adoc:72]: Nitpick: `return PapayaItemProviderAdapterFactory::new`

File: packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskEMFConfiguration.java [hunk 6]
```diff
@@ -26,7 +27,12 @@
...
     @Bean
-    public AdapterFactory taskAdapterFactory() {
-        return new TaskItemProviderAdapterFactory();
+    public ComposedAdapterFactory.Descriptor taskAdapterFactoryDescriptor() {
+        return new ComposedAdapterFactory.Descriptor() {
+            @Override
+            public AdapterFactory createAdapterFactory() {
+                return new TaskItemProviderAdapterFactory();
+            }
+        };
```
Comment (pcdavid) [inline packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskEMFConfiguration.java]: `TaskItemProviderAdapterFactory::new`

File: packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/configuration/FlowEMFConfiguration.java [hunk 7]
```diff
@@ -27,8 +28,12 @@
...
     @Bean
-    public AdapterFactory flowAdapterFactory() {
-        return new FlowItemProviderAdapterFactory();
+    public ComposedAdapterFactory.Descriptor flowAdapterFactoryDescriptor() {
+        return new ComposedAdapterFactory.Descriptor() {
+            @Override
+            public AdapterFactory createAdapterFactory() {
+                return new FlowItemProviderAdapterFactory();
+            }
+        };
```
Comment (pcdavid) [inline packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/configuration/FlowEMFConfiguration.java]: `FlowItemProviderAdapterFactory::new`

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/relatedelements/services/OutgoingTreeDescriptionProvider.java [hunk 8]
```diff
@@ -118,18 +118,21 @@ private String getNodeLabel(VariableManager variableManager) {
         if (self instanceof EReference eReference) {
             result = this.labelService.getStyledLabel(eReference).toString();
             var optionalRootEObject = variableManager.get(VariableManager.SELF, EObject.class);
-            if (optionalRootEObject.isPresent()) {
-                result = this.getDisplayName(eReference, optionalRootEObject.get());
+            var optAdapterFactory = variableManager.get(IEditingContext.EDITING_CONTEXT, IEMFEditingContext.class)
+                    .map(IEMFEditingContext::getDomain)
+                    .map(AdapterFactoryEditingDomain::getAdapterFactory);
```
Comment (pcdavid) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/relatedelements/services/OutgoingTreeDescriptionProvider.java]: It's small, but this pattern now gets repeated a lot. I wonder if we should add `IEMFEditingContext.getAdapterFactory`.

File: packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/configuration/emf/EMFAdapterFactoryConfiguration.java [hunk 9]
```diff
@@ -36,63 +37,124 @@
...
     @Bean
-    public AdapterFactory viewAdapterFactory() {
-        return new ViewItemProviderAdapterFactory();
+    public ComposedAdapterFactory.Descriptor viewAdapterFactoryDescriptor() {
+        return new ComposedAdapterFactory.Descriptor() {
+            @Override
+            public AdapterFactory createAdapterFactory() {
+                return new ViewItemProviderAdapterFactory();
+            }
+        };
```
Comment (pcdavid) [inline packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/configuration/emf/EMFAdapterFactoryConfiguration.java]: All of these in this class could be shortened to Class::new.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultEditService.java [hunk 10]
```diff
@@ -127,19 +124,23 @@ public List<ChildCreationDescription> getChildCreationDescriptions(IEditingConte
...
+                    AdapterFactoryEditingDomain adapterFactoryEditingDomain = optAdapterFactoryEditingDomain.get();
+                    Adapter adapter = adapterFactoryEditingDomain.getAdapterFactory().adapt(eObject, IEditingDomainItemProvider.class);
 
-                Adapter adapter = editingDomain.getAdapterFactory().adapt(eObject, IEditingDomainItemProvider.class);
+                    if (adapter instanceof IEditingDomainItemProvider editingDomainItemProvider && editingDomainItemProvider instanceof Helper helper) {
+
+                        Collection<?> newChildDescriptors = adapterFactoryEditingDomain.getNewChildDescriptors(eObject, null);
+
+                        List<CommandParameter> commandParameters = newChildDescriptors.stream().filter(CommandParameter.class::isInstance).map(CommandParameter.class::cast)
+                                .filter(commandParameter -> optionalEClassReference.map(eClassReference -> eClassReference.isInstance(commandParameter.getValue())).orElse(true)).toList();
```
Comment (pcdavid) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultEditService.java]: Formatting.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/validation/services/EMFValidationService.java [hunk 11]
```diff
@@ -99,27 +102,41 @@ private List<Object> validate(IEMFEditingContext editingContext) {
...
         return new Diagnostician(this.eValidatorRegistry) {
             @Override
             public String getObjectLabel(EObject eObject) {
-                IItemLabelProvider itemLabelProvider = (IItemLabelProvider) EMFValidationService.this.composedAdapterFactory.adapt(eObject, IItemLabelProvider.class);
+
+                var adapterFactories = new ArrayList<>();
+                for (org.eclipse.emf.edit.provider.ComposedAdapterFactory.Descriptor composedAdapterFactoryDescriptor : EMFValidationService.this.composedAdapterFactoryDescriptors) {
+                    adapterFactories.add(composedAdapterFactoryDescriptor.createAdapterFactory());
+                }
+                var composedAdapterFactory = new ComposedAdapterFactory(adapterFactories.toArray(AdapterFactory[]::new));
```
Comment (pcdavid) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/validation/services/EMFValidationService.java]: `eObject.eResource().getResourceSet().getAdapterFactories()`?

File: packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/library/publishers/JavaStandardLibraryPublisher.java [hunk 12]
```diff
@@ -74,7 +79,11 @@ public void publish(PublishPapayaLibraryCommand command) {
             return;
         }
 
-        AdapterFactoryEditingDomain editingDomain = this.editingDomainFactory.createEditingDomain();
+        ComposedAdapterFactory composedAdapterFactory = new ComposedAdapterFactory();
+        composedAdapterFactory.addAdapterFactory(new EcoreAdapterFactory());
+        composedAdapterFactory.addAdapterFactory(new ReflectiveItemProviderAdapterFactory());
+        composedAdapterFactory.addAdapterFactory(new PapayaItemProviderAdapterFactory());
+        AdapterFactoryEditingDomain editingDomain = new AdapterFactoryEditingDomain(composedAdapterFactory, new BasicCommandStack());
```
Comment (pcdavid) [inline packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/library/publishers/JavaStandardLibraryPublisher.java]: Not clear to me why this change (and the other similar ones) are needed?

**Review by pcdavid — CHANGES_REQUESTED** [review]
Minor stuff.

File: packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/library/publishers/JavaStandardLibraryPublisher.java (hunk 12 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/library/publishers/JavaStandardLibraryPublisher.java]: The goal was to be able to dispose the composedAdapterFactory at the end of the method.
But I forgot to dispose it, and I don't have to modify this part to do that.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/validation/services/EMFValidationService.java (hunk 11 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/validation/services/EMFValidationService.java]: eObject.eResource().getResourceSet().getAdapterFactories() returns an empty list here

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultEditService.java (hunk 10 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultEditService.java]: Done

File: packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/configuration/emf/EMFAdapterFactoryConfiguration.java (hunk 9 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-infrastructure/src/main/java/org/eclipse/sirius/web/infrastructure/configuration/emf/EMFAdapterFactoryConfiguration.java]: Done

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/relatedelements/services/OutgoingTreeDescriptionProvider.java (hunk 8 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/relatedelements/services/OutgoingTreeDescriptionProvider.java]: I'm not sure about that.
I don't think it is the role of IEMFEditingContext to do that.

File: packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/configuration/FlowEMFConfiguration.java (hunk 7 above)
Comment (AxelRICHARD) [reply packages/starters/backend/sirius-components-flow-starter/src/main/java/org/eclipse/sirius/components/flow/starter/configuration/FlowEMFConfiguration.java]: Done.

File: packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskEMFConfiguration.java (hunk 6 above)
Comment (AxelRICHARD) [reply packages/starters/backend/sirius-components-task-starter/src/main/java/org/eclipse/sirius/components/task/starter/configuration/TaskEMFConfiguration.java]: Done

File: CHANGELOG.adoc (hunk 5 above)
Comment (AxelRICHARD) [reply CHANGELOG.adoc:72]: Done

File: packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/configuration/EMFConfiguration.java (hunk 2 above)
Comment (AxelRICHARD) [reply packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/configuration/EMFConfiguration.java]: Done

File: packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/configuration/EMFConfiguration.java (hunk 1 above)
Comment (AxelRICHARD) [reply packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/configuration/EMFConfiguration.java:66]: Done

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultContentService.java (hunk 4 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultContentService.java]: eObject.eResource().getResourceSet().getAdapterFactories() returns an empty list here

File: packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultEMFLabelService.java (hunk 3 above)
Comment (AxelRICHARD) [reply packages/emf/backend/sirius-components-emf/src/main/java/org/eclipse/sirius/components/emf/services/DefaultEMFLabelService.java]: eObject.eResource().getResourceSet().getAdapterFactories() returns an empty list here

File: packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/library/publishers/ReactorLibraryPublisher.java [hunk 13]
```diff
@@ -95,6 +96,9 @@ public void publish(PublishPapayaLibraryCommand command) {
             var reactiveStreams003Library = optionalReactiveStreams003Library.get();
             this.createReactor(command, editingDomain.getResourceSet(), List.of(java003Library, reactiveStreams003Library));
         }
+        if (editingDomain.getAdapterFactory() instanceof ComposedAdapterFactory composedAdapterFactory) {
```
Comment (pcdavid) [inline packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/library/publishers/ReactorLibraryPublisher.java]: Not sure it would make a difference in practice, but shouldnt' we test for `instanceof IDisposable` instead? It's what org.eclipse.emf.edit.provider.ComposedAdapterFactory.dispose() does on its individual components.

**Review by pcdavid — APPROVED** [review]
Approved because my previous remarks have been taken into account, but @sbegaudeau should probably get a look too before we merge.

File: packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/library/publishers/ReactorLibraryPublisher.java (hunk 13 above)
Comment (AxelRICHARD) [reply packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/services/library/publishers/ReactorLibraryPublisher.java]: ok, done

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultContentService.java [hunk 14]
```diff
@@ -32,21 +34,28 @@
 @Service
 public class DefaultContentService implements IDefaultContentService {
 
-    private final ComposedAdapterFactory composedAdapterFactory;
+    private final List<Descriptor> composedAdapterFactoryDescriptors;
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultContentService.java:37]: I suspect that we should end up with our own registry instead of just a list of descriptors but I don't think that it would have an impact right now.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultContentService.java [hunk 15]
```diff
@@ -32,21 +34,28 @@
...
     @Override
     public List<Object> getContents(Object object) {
         List<Object> contents = new ArrayList<>();
         if (object instanceof EObject eObject) {
-            Adapter adapter = this.composedAdapterFactory.adapt(eObject, IEditingDomainItemProvider.class);
+            var adapterFactories = new ArrayList<>();
+            for (Descriptor composedAdapterFactoryDescriptor : this.composedAdapterFactoryDescriptors) {
+                adapterFactories.add(composedAdapterFactoryDescriptor.createAdapterFactory());
+            }
+            var composedAdapterFactory = new ComposedAdapterFactory(adapterFactories.toArray(AdapterFactory[]::new));
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/object/services/DefaultContentService.java]: You don't need to switch to an array, there's a constructor using a collection (you just need to type the list properly line 47)

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/validation/services/EMFValidationService.java [hunk 16]
```diff
@@ -99,27 +102,41 @@ private List<Object> validate(IEMFEditingContext editingContext) {
 
         Map<Object, Object> options = new HashMap<>();
         options.put(Diagnostician.VALIDATE_RECURSIVELY, true);
+
+
         Diagnostician diagnostician = this.getNewDiagnostician();
 
-        return domain.getResourceSet().getResources().stream()
+        var validate = domain.getResourceSet().getResources().stream()
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/validation/services/EMFValidationService.java]: `vaildate`? It's a list of diagnostics

File: packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/configuration/PapayaEMFConfiguration.java [hunk 17]
```diff
@@ -26,7 +27,12 @@
...
     @Bean
-    public AdapterFactory papayaAdapterFactory() {
-        return new PapayaItemProviderAdapterFactory();
+    public ComposedAdapterFactory.Descriptor papayaAdapterFactoryDescriptor() {
+        return new ComposedAdapterFactory.Descriptor() {
+            @Override
+            public AdapterFactory createAdapterFactory() {
+                return new PapayaItemProviderAdapterFactory();
+            }
+        };
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/configuration/PapayaEMFConfiguration.java]: I think we can use the same pattern

File: packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/ProjectTableRepresentationDescriptionProvider.java [hunk 18]
```diff
@@ -155,40 +154,49 @@ private Function<VariableManager, List<Object>> getSemanticColumnElementsProvide
...
-                PapayaFactory.eINSTANCE.createTag(),
-                PapayaFactory.eINSTANCE.createTask(),
-                PapayaFactory.eINSTANCE.createTypeParameter()
-        );
-
-        var provider = new StructuralFeatureToDisplayNameProvider(new DisplayNameProvider(this.composedAdapterFactory));
-        for (var eObject : objects) {
-            this.addStructuralFeature(result, provider.getColumnsStructuralFeaturesDisplayName(eObject, eObject.eClass()));
+
+        var adapterFactory = Optional.of(editingContext)
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-papaya/src/main/java/org/eclipse/sirius/web/papaya/representations/table/ProjectTableRepresentationDescriptionProvider.java]: optionalAdapterFactory

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/forms/FormWithTableDescriptionProvider.java [hunk 19]
```diff
@@ -359,21 +361,28 @@ private BiFunction<VariableManager, Object, List<Object>> getCellOptionsProvider
...
-    private Map<EStructuralFeature, String> getColumnsStructuralFeaturesDisplayName(EObject eObject, EClass eClass) {
+    private Map<EStructuralFeature, String> getColumnsStructuralFeaturesDisplayName(IEditingContext editingContext, EObject eObject, EClass eClass) {
         Map<EStructuralFeature, String> featureToDisplayName = new LinkedHashMap<>();
-        EList<EStructuralFeature> eAllStructuralFeatures = eClass.getEAllStructuralFeatures();
-        for (EStructuralFeature eStructuralFeature : eAllStructuralFeatures) {
-            if (eStructuralFeature instanceof EAttribute && !eStructuralFeature.isMany() && !eStructuralFeature.isDerived()) {
-                featureToDisplayName.put(eStructuralFeature, this.getDisplayName(eObject, eStructuralFeature));
-            } else if (eStructuralFeature instanceof EReference ref && !eStructuralFeature.isDerived() && !ref.isContainment()) {
-                featureToDisplayName.put(eStructuralFeature, this.getDisplayName(eObject, eStructuralFeature));
+        var adapterFactory = Optional.of(editingContext)
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/services/forms/FormWithTableDescriptionProvider.java]: optionalAdapterFactory

**Review by sbegaudeau — COMMENTED** [review]
I'll test it manually, rebase it and merge it
