### PR TITLE
[5147] Add impact analysis before updating a library

### LINKED ISSUE #5147: Add impact analysis before updating a library
* [x] **I have checked that this feature has not yet been suggested by someone else.**

### Expected behavior
The _Update Library_ contextual menu entry should trigger an impact analysis before performing the update. 
The impact analysis report should (at least) provide the following information:
- References that will be broken by the update (new proxies that cannot be resolved)
- References that will be fixed by the updates (old proxies that can now be resolved)

In addition, the impact analysis report could display the following information:
- List of references that have been updated (from target@v1 to target@v2)
- Number of new elements in the editing context
- Number of deleted elements in the editing context

### PR DESCRIPTION
**Pull request by gdaniel**
Fixes 
- https://github.com/eclipse-sirius/sirius-web/issues/5147

Based on:
- https://github.com/eclipse-sirius/sirius-web/pull/5124
- https://github.com/eclipse-sirius/sirius-web/pull/5253

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java [hunk 1]
```diff
@@ -65,14 +79,32 @@ public Optional<IEditingContextSnapshot> createSnapshot(IEditingContext editingC
...
+            result = Optional.of(new EditingContextSnapshot(snapshotDocuments, libraryAdapterResourcesMap, initialDependencies));
         }
         return result;
     }
 
     @Override
-    public void restoreSnapshot(IEditingContext editingContext, IEditingContextSnapshot snapshot) {
+    public void restoreSnapshot(IEditingContext editingContext, IEditingContextSnapshot snapshot, ICause cause) {
         if (editingContext instanceof EditingContext siriusWebEditingContext && snapshot instanceof EditingContextSnapshot siriusWebSnapshot) {
+            List<AggregateReference<SemanticData, UUID>> dependencies = new UUIDParser().parse(editingContext.getId())
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java]: Performing an update to compute the impact analysis report will change the dependencies of the editing context's semantic data, so we need to reset them to their original values once we restore the snapshot. If we don't, the editing context will look ok until we reload it.

I am not sure this is the way to go, but I didn't find a satisfying alternative

File: packages/trees/frontend/sirius-components-trees/src/treeitems/context-menu/TreeItemContextMenu.tsx [hunk 2]
```diff
@@ -73,6 +73,7 @@ export const TreeItemContextMenu = ({
         <TreeItemMenuContextComponent
           editingContextId={editingContextId}
           item={item}
+          entry={null}
```
Comment (gdaniel) [inline packages/trees/frontend/sirius-components-trees/src/treeitems/context-menu/TreeItemContextMenu.tsx:76]: I don't know if I should pass the `entry` to the component (and set it as `null` for frontend-only entries), or pass the `withImpactAnalysis` property. I went for the `entry` assuming this could be helpful in the future, but this `null` value is dubious at best.

File: packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/libraries/LibraryControllerIntegrationTests.java [hunk 3]
```diff
@@ -86,7 +86,7 @@ public class LibraryControllerIntegrationTests extends AbstractIntegrationTests
     private ISemanticDataSearchService semanticDataSearchService;
 
     @Autowired
-    private IObjectService objectService;
+    private IObjectSearchService objectSearchService;
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web/src/test/java/org/eclipse/sirius/web/application/controllers/libraries/LibraryControllerIntegrationTests.java]: Since I was looking at this package I fixed this deprecated dependency

File: packages/sirius-web/backend/sirius-web-e2e-tests/src/main/java/org/eclipse/sirius/web/e2e/tests/templates/TablePapayaTemplatesProvider.java [hunk 4]
```diff
@@ -35,8 +35,8 @@ public class TablePapayaTemplatesProvider implements IProjectTemplateProvider {
 
     @Override
     public List<ProjectTemplate> getProjectTemplates() {
-        var flowTemplate = new ProjectTemplate(TABLE_PAPAYA_TEMPLATE_ID, "PapayaTable", "/project-templates/Papaya.png", List.of(new ProjectTemplateNature(PAPAYA_NATURE)));
-        return List.of(flowTemplate);
+        var papayaTemplate = new ProjectTemplate(TABLE_PAPAYA_TEMPLATE_ID, "PapayaTable", "/project-templates/Papaya.png", List.of(new ProjectTemplateNature(PAPAYA_NATURE)));
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-e2e-tests/src/main/java/org/eclipse/sirius/web/e2e/tests/templates/TablePapayaTemplatesProvider.java:38]: Fixed a typo in a class I used as inspiration

File: CHANGELOG.adoc [hunk 5]
```diff
@@ -137,6 +137,8 @@ public class CanEditProjectCapabilityVoter implements ICapabilityVoter {
 ----
 - https://github.com/eclipse-sirius/sirius-web/issues/5181[#5181] [sirius-web] Remove the contribution that contribute the link to libraries to the `navigationBarMenuEntryExtensionPoint` extension point.
 The link to libraries has become a standard menu item which can be hidden providing a `ICapabilityVoter` with the type `Library` and the capability `view`.
+- https://github.com/eclipse-sirius/sirius-web/issues/5147[#5147] [sirius-web] The `EditingContextSnapshotService` now handles semantic data's dependencies.
+The method `void restore(IEditingContext, IEditingContextSnapshot)` has been updated to `void restore(IEditingContext, IEditingContextSnapshot, ICause cause)` to reflect this change.
```
Comment (sbegaudeau) [inline CHANGELOG.adoc]: If there is a cause, it should be the first parameter, always. Otherwise it should be the editing context, if it is present

File: CHANGELOG.adoc [hunk 6]
```diff
@@ -205,6 +207,10 @@ The dialog can now display an impact analysis report, but isn't in charge of ret
 - https://github.com/eclipse-sirius/sirius-web/issues/5118[#5118] [tree] Add support for impact analysis in tree item contextual menu actions.
 - https://github.com/eclipse-sirius/sirius-web/issues/5123[#5123] [tree] Add support for tree item context menu action impact analysis in the view DSL.
 - https://github.com/eclipse-sirius/sirius-web/issues/5185[#5185] [sirius-web] Hide the download button instead of disabling it when the download capability is disabled.
+- https://github.com/eclipse-sirius/sirius-web/issues/5147[#5147] [sirius-web] Add impact analysis before performing a library update.
+The impact analysis report displays the following information:
+* Number of references that will be broken by the update (new proxies that won't be resolved after the update)
```
Comment (sbegaudeau) [inline CHANGELOG.adoc]: What do you mean by broken? Those proxies will be removed from the model right? You won't save models with broken proxies? We have always worked under the assumption that models are properly resolved in the database.

File: packages/core/frontend/sirius-components-core/src/modals/impact-analysis/ImpactAnalysisDialog.tsx [hunk 7]
```diff
@@ -161,7 +161,7 @@ const ReportViewer = ({
                 <ListItemIcon sx={listItemIconStyle}>
                   <FiberManualRecordIcon sx={iconStyle} />
                 </ListItemIcon>
```
Comment (sbegaudeau) [inline packages/core/frontend/sirius-components-core/src/modals/impact-analysis/ImpactAnalysisDialog.tsx:163]: This doesn't have to use an expression

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java [hunk 8]
```diff
@@ -68,14 +82,32 @@ public Optional<IEditingContextSnapshot> createSnapshot(IEditingContext editingC
...
+                    .toList();
+
+            result = Optional.of(new EditingContextSnapshot(snapshotDocuments, libraryAdapterResourcesMap, initialDependencies));
         }
         return result;
     }
 
     @Override
-    public void restoreSnapshot(IEditingContext editingContext, IEditingContextSnapshot snapshot) {
+    public void restoreSnapshot(IEditingContext editingContext, IEditingContextSnapshot snapshot, ICause cause) {
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java]: The cause should be the first parameter

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java (hunk 1 above)
Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java]: The entire premise of the mechanism to compute the impact analysis is based on the fact that there won't be any change in the system (i.e. the database). This cannot be accepted, there has to be another way to do this. I'm not sure why would that be necessary.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/api/IEditingContextSnapshotService.java [hunk 9]
```diff
@@ -25,5 +26,5 @@ public interface IEditingContextSnapshotService {
 
     Optional<IEditingContextSnapshot> createSnapshot(IEditingContext editingContext);
 
-    void restoreSnapshot(IEditingContext editingContext, IEditingContextSnapshot snapshot);
+    void restoreSnapshot(IEditingContext editingContext, IEditingContextSnapshot snapshot, ICause cause);
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/api/IEditingContextSnapshotService.java]: Now that I've seen why this parameter has been added, I think that it should be removed

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/api/IUpdateLibraryExecutor.java [hunk 10]
```diff
@@ -0,0 +1,30 @@
...
+import org.eclipse.sirius.components.representations.IStatus;
+
+/**
+ * Used to execute a library update.
+ *
+ * @author gdaniel
+ */
+public interface IUpdateLibraryExecutor {
+
+    IStatus updateLibrary(IEditingContext editingContext, UUID libraryId, ICause cause);
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/api/IUpdateLibraryExecutor.java]: The cause should be first

File: packages/trees/frontend/sirius-components-trees/src/treeitems/context-menu/TreeItemContextMenu.tsx (hunk 2 above)
Comment (sbegaudeau) [reply packages/trees/frontend/sirius-components-trees/src/treeitems/context-menu/TreeItemContextMenu.tsx:76]: It indeed seems odd, we may need two signature for frontend and backend entries

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
I haven't tested it and there may be some small minor issues remaining but the core problem is the fact that the computation of the impact analysis would have a side effect.

File: CHANGELOG.adoc (hunk 6 above)
Comment (gdaniel) [reply CHANGELOG.adoc]: I didn't know about this assumption, and I just realized you can't upload a model that has unresolved proxies.
I don't think I understand why Sirius Web makes this assumption.

Looking at this feature, allowing proxies ensures that switching from v1 to v2 to v1 back always restores the initial state. If we remove the proxies we lose information, which doesn't seem right from my point of view.

I assume I am missing a key point here.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java (hunk 1 above)
Comment (gdaniel) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java]: I can probably work at the editing context level and replace the resources without changing the dependencies.
I didn't want to go that way because it felt odd to compute the impact analysis on "something else" than the actual operation we want to perform.

If this compromise is fine for you I can work in this direction.

File: CHANGELOG.adoc (hunk 6 above)
Comment (sbegaudeau) [reply CHANGELOG.adoc]: > I didn't know about this assumption, and I just realized you can't upload a model that has unresolved proxies.
I don't think I understand why Sirius Web makes this assumption

We guarantee that the data are not broken to be able to perform any kind of operation free of mind. Since we load / save everything at once, we don't want to try to resolve a proxy while we are working on the data.

> Looking at this feature, allowing proxies ensures that switching from v1 to v2 to v1 back always restores the initial state. If we remove the proxies we lose information, which doesn't seem right from my point of view.

Wouldn't that be the responsibility of some versioning system. If I migrate my code to another version of Spring Boot with tons of API breaks and save my file, close my editor and do something else for a while. The information is lost too, Git saves this information for me and it allows me to go back but versioning is not in the scope of Sirius Web. As soon as we are out of the stack of undo/redo of the editor, the information is lost too in VS Code for example.

Having broken models in memory to keep some information to go back to a previous version is thus not our concern.

Comment (gdaniel) [reply CHANGELOG.adoc]: Right, this is the responsibility of the versioning system.
Based on this discussion, I'll create another PR to fix the update, because at the moment it does save proxies in the database.

Comment (gdaniel) [reply CHANGELOG.adoc]: I have created the PR with the feature we discussed https://github.com/eclipse-sirius/sirius-web/pull/5253

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java (hunk 1 above)
Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java]: I'm not sure why would that be necessary, we may need to talk directly to see how that can be fixed.

Comment (gdaniel) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java]: We discussed it, the solution we chose is to _not_ update anything in the database if we aren't performing the actual update.

File: CHANGELOG.adoc (hunk 5 above)
Comment (gdaniel) [reply CHANGELOG.adoc]: The cause has been removed, as the entry in the changelog

File: CHANGELOG.adoc (hunk 6 above)
Comment (gdaniel) [reply CHANGELOG.adoc]: I updated and clarified the changelog: the message will display references that will be broken (_and deleted_) after the update

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java (hunk 8 above)
Comment (gdaniel) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/EditingContextSnapshotService.java]: The cause has been removed

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/api/IEditingContextSnapshotService.java (hunk 9 above)
Comment (gdaniel) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/editingcontext/services/api/IEditingContextSnapshotService.java]: done

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/api/IUpdateLibraryExecutor.java (hunk 10 above)
Comment (gdaniel) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/api/IUpdateLibraryExecutor.java]: fixed

File: packages/core/frontend/sirius-components-core/src/modals/impact-analysis/ImpactAnalysisDialog.tsx (hunk 7 above)
Comment (gdaniel) [reply packages/core/frontend/sirius-components-core/src/modals/impact-analysis/ImpactAnalysisDialog.tsx:163]: Not sure I understand what you mean, should I update this as follows?
```
<ListItemIcon sx={{minWidth: 'auto'}}>
    <FiberManualRecordIcon sx={iconStyle} />
</ListItemIcon>
```

File: packages/trees/frontend/sirius-components-trees/src/treeitems/context-menu/TreeItemContextMenu.tsx (hunk 2 above)
Comment (gdaniel) [reply packages/trees/frontend/sirius-components-trees/src/treeitems/context-menu/TreeItemContextMenu.tsx:76]: I can do that but it would have a few impacts on existing menu contributions and potentially downstream applications.
The idea would be to change
```
export const treeItemContextMenuEntryExtensionPoint: ComponentExtensionPoint<TreeItemContextMenuComponentProps>
```
to
```
export const treeItemContextMenuEntryExtensionPoint: ComponentExtensionPoint<TreeItemContextMenuFrontendComponentProps>
```

We should agree on the naming, but to stay consistent, we may want to 
- Change the name of the extension point to reflect that it only contains _frontend_ contributions
- Change `TreeItemContextMenuComponentProps` to reflect that values of this type are bound to a backend menu entry

If I understood the direction tree menus are taking, I assume pure frontend menu entries will disappear in the near future (or at least be discouraged). If this is the case we will most likely not need this refactoring at all since pure frontend contributions won't be supported anymore.

I may be off though, let me know if you want me to do the refactoring I proposed above.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/UpdateLibraryExecutor.java [hunk 11]
```diff
@@ -0,0 +1,228 @@
...
+                            });
+
+                    this.editingContextDependencyLoader.loadDependencies(siriusWebEditingContext, newDependencies);
+
+                    long start = System.nanoTime();
+                    Map<EObject, Collection<Setting>> removedProxies = this.removeUnresolvedProxies(siriusWebEditingContext.getDomain().getResourceSet());
+                    Duration timeToRemoveProxies = Duration.ofNanos(System.nanoTime() - start);
+                    this.logger.trace("Removed proxies in {}ms", timeToRemoveProxies.toMillis());
+
+                    result = new Success(ChangeKind.SEMANTIC_CHANGE, Map.of(REMOVED_PROXIES_PARAMETER_KEY, removedProxies), List.of(new Message("Library " + oldLibrary.getName() + " updated to version " + newLibrary.getVersion(), MessageLevel.SUCCESS)));
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/UpdateLibraryExecutor.java:124]: I am not sure of this implementation.
I added a parameter in the `Success` with the map of unresolved proxies found after the update.
The proxies have been deleted (this is the main goal of #5252 ), and this parameter is a trace of what has been deleted. I use it in the impact analysis to compute the message to display.

This implementation allows to find proxies only once (when we want to delete them), and not re-do the same work as part of the impact analysis computation.

The thing I am not sure about though, is whether these `Success#parameters` can be used for such purpose.

**Review by sbegaudeau — APPROVED** [review]
I still have a details or two that I'll need to look a bit more carefully but it can be merged as is for now. Those are very minor internal details. I'll rebase it and merge it after the build to ensure that it will be part of tomorrow's release.
