### PR TITLE
[6192] Fix deadlock on upload of project with invalid representations

### LINKED ISSUE #6192: Uploading a projet with a representation having an unknown description ID leads to a deadlock
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [ ] **I have specified the version** :
- latest
- other: please specify
* [ ] **I have specified my environment** : 
- All
- my computer: Windows? Linux? Cloud?
- Cloud

### Screenshots

...

### Steps to reproduce

- Download a project with a portal representation
- Modify inside the IDs of the portal representation description
- Upload the project in Sirius Web

### Expected behavior

The project is rejected since invalid OR the project is correctly uploaded without the representation.

### Actual behavior

Sirius Web is stuck on the upload.

### PR DESCRIPTION
**Pull request by pcdavid**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/6192
Signed-off-by: Pierre-Charles David <pierre-charles.david@obeo.fr>

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/InputDispatcher.java [hunk 1]
```diff
@@ -105,6 +107,7 @@ private void handleInput(Sinks.One<IPayload> payloadSink, Sinks.Many<Boolean> ca
             IEditingContextEventHandler editingContextEventHandler = optionalEditingContextEventHandler.get();
             editingContextEventHandler.handle(payloadSink, changeDescriptionSink, editingContext, input);
         } else {
+            payloadSink.tryEmitValue(new ErrorPayload(input.id(), "No handler found for event: " + input));
```
Comment (gcoutable) [inline packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/InputDispatcher.java:110]: Instead of doing it inside the `else`, could we try to emit the error no matter what at the end of `#dispatch` and look in the `EmitResult` if it succeeded or failed?
This should work since `payloadSink` is a `Sinks.One`.

Comment (pcdavid) [reply packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/InputDispatcher.java:110]: > try to emit the error no matter what at the end of #dispatch and look in the EmitResult if it succeeded or failed

It might work, but this feels like abusing the API, putting it in an erroneous state (publishing two values) in the normal case.

My "instinct" would be to change the signature or `IRepresentationEventProcessor.handle()` and `IEditingContextEventHandler.handle()`: from:

```java
void handle(One<IPayload> payloadSink, Many<ChangeDescription> changeDescriptionSink, IRepresentationInput representationInput)
```

to

```java
IPayload handle(Many<ChangeDescription> changeDescriptionSink, IRepresentationInput representationInput)
```

to make it more obivious that the processor _should always provide a payload_, and le the  caller emit the payload.

With a `One<IPayload> payloadSink`, it's easy to leave code paths which never actually publish anything on it. If the payload is the return value, implementers *must* return something on every code path, which is what we expect of them.

This would be a significant API change however (at least in terms of classes impacted), so assuming this would be a good idea (which I'm not sure yet), it's probably not the moment.

Beside the code churn, the only change behavior change I see is that this would mean the payload is always sent _after the handler has fully completed_, whereas at the moment a handler can publish its payload and then continue to perform additional work before returning. Many handler already publish their payload at the end, but I've not looked at all of them.

@sbegaudeau any opinion in this?

**Comment by pcdavid** [comment]
I've reverted `bac1c4b266eb394da4afb42cb7190ea5b31858f6` in addition. It seems to be the cause of regressions in e.g. SysON when importing large SysML documents which take more that 5s to parse/validate/import.

With this version I no longer reproduce either #6192 or #6277 (same scenario) in Sirius Web not the aforementioned issue in SysON.

Compared to v2026.1.3, the overall changes in core classes (`EditingContextEventProcessor` and `InputDispatcher`) are minimal:

```
% git diff v2026.1.3 -- packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/InputDispatcher.java
diff --git c/packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/InputDispatcher.java w/packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/InputDispatcher.java
index 0c5a3e533f..45ea69fde4 100644
--- c/packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/InputDispatcher.java
+++ w/packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/InputDispatcher.java
@@ -1,5 +1,5 @@
 /*******************************************************************************
- * Copyright (c) 2025 Obeo.
+ * Copyright (c) 2025, 2026 Obeo.
  * This program and the accompanying materials
  * are made available under the terms of the Eclipse Public License v2.0
  * which accompanies this distribution, and is available at
@@ -20,13 +20,14 @@ import java.util.concurrent.atomic.AtomicReference;

 import org.eclipse.sirius.components.collaborative.api.ChangeDescription;
 import org.eclipse.sirius.components.collaborative.api.IEditingContextEventHandler;
-import org.eclipse.sirius.components.collaborative.editingcontext.api.IInputDispatcher;
 import org.eclipse.sirius.components.collaborative.api.IInputPostProcessor;
 import org.eclipse.sirius.components.collaborative.api.IInputPreProcessor;
 import org.eclipse.sirius.components.collaborative.api.IRepresentationEventProcessor;
-import org.eclipse.sirius.components.collaborative.editingcontext.api.IRepresentationEventProcessorProvider;
 import org.eclipse.sirius.components.collaborative.dto.DeleteRepresentationInput;
+import org.eclipse.sirius.components.collaborative.editingcontext.api.IInputDispatcher;
+import org.eclipse.sirius.components.collaborative.editingcontext.api.IRepresentationEventProcessorProvider;
 import org.eclipse.sirius.components.collaborative.representations.api.IRepresentationEventProcessorRegistry;
+import org.eclipse.sirius.components.core.api.ErrorPayload;
 import org.eclipse.sirius.components.core.api.IEditingContext;
 import org.eclipse.sirius.components.core.api.IInput;
 import org.eclipse.sirius.components.core.api.IPayload;
@@ -34,6 +35,7 @@ import org.eclipse.sirius.components.core.api.IRepresentationInput;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 import org.springframework.stereotype.Service;
+
 import reactor.core.publisher.Sinks;

 /**
@@ -105,6 +107,7 @@ public class InputDispatcher implements IInputDispatcher {
             IEditingContextEventHandler editingContextEventHandler = optionalEditingContextEventHandler.get();
             editingContextEventHandler.handle(payloadSink, changeDescriptionSink, editingContext, input);
         } else {
+            payloadSink.tryEmitValue(new ErrorPayload(input.id(), "No handler found for event: " + input));
             this.logger.warn("No handler found for event: {}", input);
         }
     }
@@ -116,6 +119,7 @@ public class InputDispatcher implements IInputDispatcher {
             IRepresentationEventProcessor representationEventProcessor = optionalRepresentationEventProcessor.get();
             representationEventProcessor.handle(payloadSink, changeDescriptionSink, representationInput);
         } else {
+            payloadSink.tryEmitValue(new ErrorPayload(representationInput.id(), "No representation event processor found for event: " + representationInput));
             this.logger.warn("No representation event processor found for event: {}", representationInput);
         }
     }
```

**Review by sbegaudeau — APPROVED** [review]
I'll wait for the build, merge it and release v2026.1.5 just after
