### PR TITLE
[5802] Add ITreeInput in tree executors to check received input

### LINKED ISSUE #5802: Add input parameter in ISingleClickTreeItemContextMenuEntryExecutor#canExecute
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- All

With the current implementation, the `canExecute` method has only access to the `treeDescription`, which is not enough to find which action triggered the execution.

As an exemple, the current implementation in `RemoveLibrarySingleClickTreeItemContextMenuEntryExecutor` is as follows:

```java
public boolean canExecute(TreeDescription treeDescription) {
    return Objects.equals(treeDescription.getId(), ExplorerDescriptionProvider.DESCRIPTION_ID);
}
```

This means that this executor can be called for any `SingleClickTreeItemContextMenuEntry` (see `InvokeSingleClickTreeItemContextMenuEntryEventHandler#handle)`, which is clearly wrong. It should be able to find which actual entry was clicked by inspecting `InvokeSingleClickTreeItemContextMenuEntryInput#menuEntryId()`.

This issue is not visible for now because `RemoveLibrarySingleClickTreeItemContextMenuEntryExecutor` is the only implementation of this interface with this condition.
The other implementation (`ViewSingleClickTreeItemContextMenuEntryExecutor`) works for view-based trees, these trees aren't used by the Sirius Web explorer.

### PR DESCRIPTION
**Pull request by gdaniel**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/5802
Fixes #5802 

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [x] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/RemoveLibrarySingleClickTreeItemContextMenuEntryExecutor.java [hunk 1]
```diff
@@ -78,14 +79,21 @@ public RemoveLibrarySingleClickTreeItemContextMenuEntryExecutor(IObjectSearchSer
     }
 
     @Override
-    public boolean canExecute(TreeDescription treeDescription) {
-        return Objects.equals(treeDescription.getId(), ExplorerDescriptionProvider.DESCRIPTION_ID);
+    public boolean canExecute(TreeDescription treeDescription, ITreeInput treeInput) {
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/RemoveLibrarySingleClickTreeItemContextMenuEntryExecutor.java:82]: I entirely removed the previous version of the condition. I don't think it makes sense to check if the `treeDescription` is the explorer. We don't do it in other handlers: for example `DeleteTreeItemHandler` only checks the type of the input, not the tree description.
This allows to reuse this handler in downstream applications without duplicating its code.
Let me know if you disagree.

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/RemoveLibrarySingleClickTreeItemContextMenuEntryExecutor.java [hunk 2]
```diff
@@ -78,14 +79,21 @@ public RemoveLibrarySingleClickTreeItemContextMenuEntryExecutor(IObjectSearchSer
...
+        }
+        return result;
     }
 
     @Override
     public IStatus execute(IEditingContext editingContext, TreeDescription treeDescription, Tree tree, TreeItem treeItem, String treeItemMenuContextEntryId, ITreeInput treeInput) {
         IStatus result = new Failure("Something went wrong while handling the action");
-        if (editingContext instanceof EditingContext siriusWebEditingContext) {
+        if (editingContext instanceof EditingContext siriusWebEditingContext
+                && (treeInput instanceof InvokeSingleClickTreeItemContextMenuEntryInput || treeInput instanceof InvokeTreeImpactAnalysisInput)) {
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/RemoveLibrarySingleClickTreeItemContextMenuEntryExecutor.java:96]: I added this extra check to align with other handlers we have

**Review by sbegaudeau — APPROVED** [review]

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/RemoveLibrarySingleClickTreeItemContextMenuEntryExecutor.java (hunk 1 above)
Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/RemoveLibrarySingleClickTreeItemContextMenuEntryExecutor.java:82]: The fact that we have to consider the impact analysis is a bit odd, but it's not a significant issue

Comment (gdaniel) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/views/explorer/services/RemoveLibrarySingleClickTreeItemContextMenuEntryExecutor.java:82]: We could maybe add an interface above `InvokeSingleClickTreeItemContextMenuEntryInput` and `InvokeTreeImpactAnalysisInput` with a `menuEntryId()` method.
Since they both invoke a tool this could make sense.
