### PR TITLE
[6192] Fix deadlock when importing a project

### LINKED ISSUE #6192: Uploading a projet with a representation having an unknown description ID leads to a deadlock
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [ ] **I have specified the version** :
- latest
- other: please specify
* [ ] **I have specified my environment** : 
- All
- my computer: Windows? Linux? Cloud?
- Cloud

### Screenshots

...

### Steps to reproduce

- Download a project with a portal representation
- Modify inside the IDs of the portal representation description
- Upload the project in Sirius Web

### Expected behavior

The project is rejected since invalid OR the project is correctly uploaded without the representation.

### Actual behavior

Sirius Web is stuck on the upload.

### PR DESCRIPTION
**Pull request by theogiraudet**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/6192

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/RepresentationProjectContentImportParticipant.java [hunk 1]
```diff
@@ -172,7 +181,11 @@ private void createRepresentations(UUID inputId, ProjectZipContent projectZipCon
             String objectId = this.getNewObjectId(targetObjectURI, documentIdMapping, semanticIdMapping);
 
             CreateRepresentationInput createRepresentationInput = new CreateRepresentationInput(inputId, editingContextEventProcessor.getEditingContextId(), descriptionURI, objectId, representationImportData.label());
+            var timeoutFallback = Mono.just(new ErrorPayload(inputId, this.messageService.timeout()))
+                .doOnSuccess(payload -> this.logger.warn("Timeout fallback for the representation upload"));
+
```
Comment (sbegaudeau) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/RepresentationProjectContentImportParticipant.java]: Instead of adding yet another timeout fallback, the existing one in EditingContextEventProcessorRegistry should be moved in EditingContextEventProcessor#handle. Probably by using `Future#get(timeout, unit)` and returning a proper ErrorPayload in case of `TimeoutException`

**Review by sbegaudeau — CHANGES_REQUESTED** [review]

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/RepresentationProjectContentImportParticipant.java (hunk 1 above)
Comment (pcdavid) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/RepresentationProjectContentImportParticipant.java]: So like [this](https://github.com/eclipse-sirius/sirius-web/pull/1752/changes)?

Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/RepresentationProjectContentImportParticipant.java]: With a removal of the code doing pretty much the same thing in `EditingContextEventProcessorRegistry#dispatchEvent` and at least a test, yes 😄

Comment (theogiraudet) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/RepresentationProjectContentImportParticipant.java]: Doing as proposed by pcdavid will probably require to split the `EditingContextEventProcessor`, since we will reach the limit of 8 injected dependencies by adding the message service.

Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/project/services/RepresentationProjectContentImportParticipant.java]: We could do that in two steps, move the code first as is, perform the internationalization later. I have some code that will help splitting this class but it will take some time to be mergeable

**Comment by sbegaudeau** [comment]
Quick automatic review (please ignore this message)

  Pull Request Status:
  PR: [6192] Fix deadlock when importing a project (https://github.com/eclipse-sirius/sirius-web/pull/6193)
  CI Status: Fail - (Metadata Review)
  Size: Manageable - (29 additions, 1 deletions across 6 files)


  Recommendation: Hold off on review until CI checks are resolved. The failure in "Metadata Review" is likely due to missing labels (area:, type: bug, difficulty:) and a milestone on the linked issue #6192 (https://github.com/eclipse-sirius/sirius-web/issues/6192).


  Summary:
  This pull request successfully addresses the deadlock encountered during project import when a representation refers to an unknown description ID. By introducing a 5-second timeout on the representation creation process and providing an internationalized error fallback, the PR prevents the import process from blocking indefinitely. While the logic is sound, several architectural and stylistic violations must be addressed to align with the project's strict standards.

  <details>
  <summary>🚨 Critical & Architectural Issues</summary>


   - Missing Null Safety Check: The newly injected IMessageService in RepresentationProjectContentImportParticipant is not verified for nullity.
    > Rule (Java Backend 2): "Every dependency injected into a constructor MUST be explicitly verified as non-null using Objects.requireNonNull()."


   1   public RepresentationProjectContentImportParticipant(ObjectMapper objectMapper, List<IRepresentationImporterUpdateService> diagramImporterUpdateServices, IEditingContextEventProcessorRegistry editingContextEventProcessorRegistry,
   2       IMessageService messageService) {
   3       this.objectMapper = Objects.requireNonNull(objectMapper);
   4       this.diagramImporterUpdateServices = Objects.requireNonNull(diagramImporterUpdateServices);
   5       this.editingContextEventProcessorRegistry = Objects.requireNonNull(editingContextEventProcessorRegistry);
   6       this.messageService = Objects.requireNonNull(messageService); // Missing this
   7   }


   - Outdated Copyright Header: The copyright year in RepresentationProjectContentImportParticipant.java has not been updated.
    > Rule (Java Backend 13): "The copyright header of any file modified MUST be updated to contain the current year (e.g. 'Copyright (c) 2024, 2026 Obeo.')."

    Update Copyright (c) 2025 Obeo. to Copyright (c) 2025, 2026 Obeo..


   - Missing Issue Metadata: The linked issue #6192 (https://github.com/eclipse-sirius/sirius-web/issues/6192) is missing required labels and a milestone, which is causing the CI metadata check to fail. Please ensure the issue has the appropriate area:, type: bug, and difficulty: labels.

  </details>


  <details>
  <summary>⚠️ Standard & Stylistic Feedback</summary>


   - Naming Convention for Optionals: The variable representationPayloadCreated should follow the project's naming convention for Optional types.
    > Rule (Java Backend 10): "Optional variables SHOULD start with the suffix optional (e.g. Optional<Project> optionalProject)." (Note: The rule says suffix but the example uses a prefix, which is the intended convention).


   1   // Suggest renaming
   2   var optionalRepresentationPayloadCreated = editingContextEventProcessor.handle(createRepresentationInput)
   3       .timeout(Duration.ofSeconds(5), timeoutFallback)
   4       // ...


   - Blocking Call in Loop: While using .blockOptional() is necessary here due to the synchronous nature of IProjectContentImportParticipant, be aware that in a loop, this can lead to a cumulative delay if multiple representations timeout. However, 5 seconds is a reasonable bound for this specific import context compared to an indefinite deadlock.

  </details>

  <details>
  <summary>✅ What Went Well</summary>


   - Excellent Internationalization: Providing both English and French translations for the new TIMEOUT message is consistent with the project's requirement for user-facing strings.
   - Clean Fallback Logic: Using a reactive timeout with a fallback to Mono.just(new ErrorPayload(...)) is a very clean way to integrate error handling into the existing stream without breaking the pipeline.
   - Surgical Fix: The change is highly focused and directly addresses the reported bug without introducing unrelated refactoring.


  </details>

**Comment by sbegaudeau** [comment]
Quick automatic review (please ignore this message)



  Pull Request Status:
  PR: [6192] Fix deadlock when importing a project (https://github.com/eclipse-sirius/sirius-web/pull/6193)
  CI Status: Fail - _(Continuous integration/Build (pull_request) is failing)_
  Size: Manageable - (12 additions, 10 deletions across 3 files)
  Mergeable: CONFLICTING - (This PR has merge conflicts that must be resolved before it can be merged)


  Summary:
  This pull request addresses a deadlock issue occurring during project imports (issue #6192) by introducing a 5-second timeout and task cancellation mechanism within the EditingContextEventProcessor. The timeout logic has been moved from the EditingContextEventProcessorRegistry to the processor itself, ensuring that blocked threads are released and a proper ErrorPayload is returned to the client. While the approach provides a necessary safety net, the implementation requires several fixes to adhere to the project's architectural and coding standards.

  <details>
  <summary>🚨 Critical & Architectural Issues</summary>


  1. Missing Null Safety Checks in Constructors
  Several dependencies are injected without the mandatory Objects.requireNonNull() check, violating the Dependency Injection & Instantiation rule (Rule 2) of the java-backend-reviewer skill.

   * `EditingContextEventProcessor.java`:


   1     // Current
   2     this.executorService = executorServiceProvider.getExecutorService(this.editingContext);
   3
   4     // Required
   5     this.executorService = Objects.requireNonNull(executorServiceProvider).getExecutorService(this.editingContext);

   * `EditingContextEventProcessorRegistry.java`:


   1     // Current
   2     this.editingContextEventProcessorFactory = editingContextEventProcessorFactory;
   3     this.representationEventProcessorRegistry = representationEventProcessorRegistry;
   4
   5     // Required
   6     this.editingContextEventProcessorFactory = Objects.requireNonNull(editingContextEventProcessorFactory);
   7     this.representationEventProcessorRegistry = Objects.requireNonNull(representationEventProcessorRegistry);


  2. Hardcoded & Non-Internationalized Error Message
  The error message returned upon timeout is hardcoded as a literal string. According to General Spring Boot Best Practices (Rule 8), all messages returned to the frontend MUST be internationalized.


   * File: EditingContextEventProcessor.java
   * Recommendation: Inject ICollaborativeMessageService and use its timeout() method, similar to the previous implementation in the registry.


   1 // Suggested change in EditingContextEventProcessor.java
   2 } catch (TimeoutException e) {
   3     future.cancel(true);
   4     result = Mono.just(new ErrorPayload(input.id(), this.messageService.timeout()));
   5 }

  </details>

  <details>
  <summary>⚠️ Standard & Stylistic Feedback</summary>


  1. CI Failure & Merge Conflicts
  The build is currently failing, and there are merge conflicts with the base branch. Please rebase on master and ensure all tests pass before requesting a final review.


  2. Timeout Duration Hardcoding
  The 5-second timeout is currently hardcoded in EditingContextEventProcessor.java. Considering this is a core component of the collaborative engine, it would be preferable to make this duration configurable via a @Value property (e.g., sirius.components.editingContext.timeout), allowing for environment-specific tuning.

  </details>

  <details>
  <summary>✅ What Went Well</summary>


   * Proper Resource Management: Correct use of future.cancel(true) ensures that the thread pool is not leaked by tasks that have timed out, provided the underlying dispatch logic is interruption-aware.
   * Monitoring: The integration with Micrometer timers is maintained correctly, ensuring that processing times (including timeouts) are accurately captured in metrics.
   * Copyright Compliance: All modified files have their copyright headers correctly updated to 2026.


  </details>

File: packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java [hunk 2]
```diff
@@ -120,18 +123,22 @@ public Mono<IPayload> handle(IInput input) {
...
+        Mono<IPayload> result = payloadSink.asMono()
+                .log(this.getClass().getName(), Level.FINEST, SignalType.ON_NEXT, SignalType.ON_ERROR)
+                .doOnError(throwable -> this.logger.warn(throwable.getMessage(), throwable));
         try {
             // Block until the event has been processed
-            future.get();
+            future.get(5, TimeUnit.SECONDS);
         } catch (InterruptedException | ExecutionException exception) {
             this.logger.warn(exception.getMessage(), exception);
+        } catch (TimeoutException e) {
```
Comment (sbegaudeau) [inline packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessor.java]: Use a meaningful variable name and log the exception

File: packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorRegistry.java [hunk 3]
```diff
@@ -87,11 +87,8 @@ public List<IEditingContextEventProcessor> getEditingContextEventProcessors() {
 
     @Override
     public Mono<IPayload> dispatchEvent(String editingContextId, IInput input) {
-        var timeoutFallback = Mono.just(new ErrorPayload(input.id(), this.messageService.timeout()))
-                .doOnSuccess(payload -> this.logger.warn("Timeout fallback for the input {}", input));
-
         return this.getOrCreateEditingContextEventProcessor(editingContextId)
-                .map(processor -> processor.handle(input).timeout(Duration.ofSeconds(5), timeoutFallback))
+                .map(processor -> processor.handle(input))
```
Comment (sbegaudeau) [inline packages/core/backend/sirius-components-collaborative/src/main/java/org/eclipse/sirius/components/collaborative/editingcontext/EditingContextEventProcessorRegistry.java:82]: The ErrorPayload is imported for nothing, does your IDE report Checkstyle errors? The message service is also unused.

**Review by sbegaudeau — CHANGES_REQUESTED** [review]
I'll update the PR and ensure that it gets merged

**Review by sbegaudeau — APPROVED** [review]
I'll merge it after the build
