### PR TITLE
[6346] Ensure forms are read only when opened on a library

### LINKED ISSUE #6346: Representation details are not read-only in the library workbench
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- All

### Steps to reproduce

1. Create a studio and publish it
2. Open the published library
3. Select a representation
4. The details view allows to edit the name of the representation

On top of that, the edited name is actually persisted in the database.

### Expected behavior

The details view should be read only

### Additional information

Forms should be read-only when they are opened on a library editing context. 
Since forms do not rely on the `readOnly` property of `WorkbenchViewComponentProps`, the backend needs to send the `canEdit=false` capability for any form on a library editing context.
This will make the entire form read-only, regardless of whether the selected element is a semantic element, a representation, or something else.

### PR DESCRIPTION
**Pull request by gdaniel**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/6346
Fixes #6346 

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [x] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?

Create a studio and publish it.
Open the created library containing the domain model.
Select the diagram representation in the explorer -> the details view is read-only.

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/capability/services/FormCapabilitiesService.java [hunk 1]
```diff
@@ -44,6 +54,14 @@ public FormCapabilitiesDTO getFormCapabilities(String editingContextId, String f
...
         if (optionalProjectId.isPresent()) {
             canEdit = this.capabilityEvaluator.hasCapability(SiriusWebCapabilities.PROJECT, optionalProjectId.get(), SiriusWebCapabilities.Project.EDIT);
+        } else {
+            // Forms in libraries should never be editable (since libraries are read-only).
+            Optional<Library> optionalLibrary = new UUIDParser().parse(editingContextId)
+                    .map(AggregateReference::<SemanticData, UUID>to)
+                    .flatMap(this.librarySearchService::findBySemanticData);
+            if (optionalLibrary.isPresent()) {
+                canEdit = false;
+            }
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/capability/services/FormCapabilitiesService.java]: I don't know if it is the correct solution to hardcode this here.
It could be provided by a `CapabilityVoter` (for `Library#edit`), but this capability doesn't exist, since libraries are designed to never be editable.

Comment (sbegaudeau) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/capability/services/FormCapabilitiesService.java]: I'll update the default to start with a pessimistic approach of canEdit = false instead. It should be enough unless I missed something. Adding additional library checks will just add some complexity down the line on other subjects.

**Review by sbegaudeau — APPROVED** [review]
I'll wait for the build and merge it

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/capability/services/FormCapabilitiesService.java (hunk 1 above)
Comment (gdaniel) [reply packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/capability/services/FormCapabilitiesService.java]: (removed my comment)
