### PR TITLE
[5368] Rename Settings menu and export action

### LINKED ISSUE #5368: The "Settings" menu and icon on tables is wrongly named
The name "Settings" (and the icon chosen) implies it gives access to some kind of configuration parameters for the table, but that's not the case.

It's a menu with a single, global _action_ to export the data to CSV.

Image

Also, the action's name "Export all data in page" is confusing too:
* Why mention "all data" if it's only the data visible in the current page?
* Why not mention that the export produces CSV?

"Export page data as CSV" would be cleaer IMO.

### PR DESCRIPTION
**Pull request by ntinsalhi-obeo**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/5368

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/tables/frontend/sirius-components-tables/src/actions/SettingsButton.tsx [hunk 1]
```diff
@@ -22,44 +22,44 @@ import { settingButtonMenuEntryExtensionPoint } from './SettingsButtonExtensionP
...
-            editingContextId={editingContextId}
-            representationId={representationId}
-            tableId={table.id}
-          />
-        ))}
-      </Menu>
-    </>
-  );
-};
+    return (
```
Comment (frouene) [inline packages/tables/frontend/sirius-components-tables/src/actions/SettingsButton.tsx]: Check your prettier configuration, the indentation should not change

File: packages/tables/frontend/sirius-components-tables/src/actions/SettingsButton.tsx [hunk 2]
```diff
@@ -22,44 +22,44 @@ import { settingButtonMenuEntryExtensionPoint } from './SettingsButtonExtensionP
 import { SettingsButtonMenuEntryProps } from './SettingsButtonExtensionPoints.types';
 
 export const SettingsButton = ({ editingContextId, representationId, table }: SettingsButtonProps) => {
```
Comment (frouene) [inline packages/tables/frontend/sirius-components-tables/src/actions/SettingsButton.tsx]: Change the component name (and file name) to maintain consistency

File: packages/tables/frontend/sirius-components-tables/src/actions/ExportDataButton.tsx [hunk 3]
```diff
@@ -77,7 +77,7 @@ export const ExportAllDataButton = ({ table }: ExportAllDataButtonProps) => {
       <ListItemIcon>
         <FileDownloadIcon fontSize="small" />
       </ListItemIcon>
-      <ListItemText>Export all data in page</ListItemText>
+      <ListItemText>Export page data as CSV</ListItemText>
```
Comment (frouene) [inline packages/tables/frontend/sirius-components-tables/src/actions/ExportDataButton.tsx:80]: Maybe rename the component name to `ExportPageDataButton`

**Review by frouene — CHANGES_REQUESTED** [review]

File: packages/tables/frontend/sirius-components-tables/src/actions/SettingsButton.tsx [hunk 4]
```diff
@@ -22,44 +22,44 @@ import { settingButtonMenuEntryExtensionPoint } from './SettingsButtonExtensionP
...
-};
+    return (
+        <>
+            <Button
+                aria-haspopup="true"
+                aria-expanded={!!state.contextMenuAnchorElement ? 'true' : undefined}
+                startIcon={<ToolsIcon />}
+                color="inherit"
+                onClick={handleClick}>
+                Tools
```
Comment (AxelRICHARD) [inline packages/tables/frontend/sirius-components-tables/src/actions/SettingsButton.tsx]: I suggest `Actions` instead of `Tools`? What do you think about? @mbats what do you think about?

Comment (AxelRICHARD) [reply packages/tables/frontend/sirius-components-tables/src/actions/SettingsButton.tsx]: after discussion with the team, `Tools` is the label taken on

**Review by frouene — APPROVED** [review]
