### PR TITLE
[6387] Set the initial position of an EdgeAnchorNode when converting …

### LINKED ISSUE #6387: The initial position of an EdgeAnchorNode can be wrong
When creating an `EdgeAnchorNode `for the first time, we can deduce its position if the base edge exists.

This would remove flickering of the edge on edge when creating it with the connector tool.

### PR DESCRIPTION
**Pull request by mcharfadi**
…the diagram

Bug: https://github.com/eclipse-sirius/sirius-web/issues/6387

# Pull request template

## General purpose
What is the main goal of this pull request?
- [ ] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts [hunk 1]
```diff
@@ -11,28 +11,53 @@
...
+import { Edge, HandleType, Node } from '@xyflow/react';
 import { GQLNodeLayoutData } from '../graphql/subscription/diagramFragment.types';
 import { GQLEdge } from '../graphql/subscription/edgeFragment.types';
 import { GQLPosition } from '../graphql/subscription/nodeFragment.types';
-import { NodeData } from '../renderer/DiagramRenderer.types';
+import { EdgeData, NodeData } from '../renderer/DiagramRenderer.types';
 import { ConnectionHandle } from '../renderer/handles/ConnectionHandles.types';
 import { convertHandles } from './convertHandles';
 
+export const getNodePositionAbsoluteFromSvgPathAndPositionRation = (
```
Comment (frouene) [inline packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts:20]: It's only used here, does it needs to be export?

File: packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts [hunk 2]
```diff
@@ -11,28 +11,53 @@
...
+  edgePath: string,
+  positionRatio: number,
+  isLayouted: boolean
```
Comment (frouene) [inline packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts:23]: always true (only call in private)

File: packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts [hunk 3]
```diff
@@ -11,28 +11,53 @@
...
+) => {
+  //Get the point on the svgPath where the EdgeAnchorNode will be placed
+  var svgPath = document.createElementNS('http://www.w3.org/2000/svg', 'path');
+  svgPath.setAttribute('d', edgePath);
+  const pathLength = svgPath.getTotalLength();
+  let points = svgPath.getPointAtLength(pathLength * 0.5);
+  if (isLayouted && positionRatio) {
```
Comment (frouene) [inline packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts:30]: does it need to be split into two variables, `positionRatio`  defined is it not enough ?

**Review by frouene — CHANGES_REQUESTED** [review]

File: packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts (hunk 3 above)
Comment (mcharfadi) [reply packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts:30]: I guess `positionRatio ` could have been of type `number | null `but I don't want to make this change here.

File: packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts (hunk 2 above)
Comment (mcharfadi) [reply packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts:23]: I'm now using it in `EdgeAnchorNode`

File: packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts (hunk 1 above)
Comment (mcharfadi) [reply packages/diagrams/frontend/sirius-components-diagrams/src/converter/edgeAnchorNodeFactory.ts:20]: I'm now using it in `EdgeAnchorNode`

**Review by frouene — APPROVED** [review]
