### PR TITLE
[6141] Ensure unique IDs for table widgets in forms

### LINKED ISSUE #6141: Table cell editing does not work when there is multiple table form widgets in a form
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** :
- All

In a form with multiple pages containing tables, editing a cell does not work correctly : it is not possible to edit a cell.
Each page contains a widget with a table, and all tables share the same ID.
When editing a cell, in EditCellEventHandler, the following line:

`var optCell = this.tableQueryService.findCellById(tableContext.getTable(), editCellInput.cellId());` search for a cell in a tableContext, but the tableContext is always the same.

This comes from the render() method of TableComponent :
`String id = variableManager.get(GetOrCreateRandomIdProvider.PREVIOUS_REPRESENTATION_ID, String. Class).orElseGet(() → UUID.randomUUID().toString());
`
In this case, the PREVIOUS_REPRESENTATION_ID is the ID of the form. So when editing a cell, the cell lookup always targets the same table (the first one created).

### PR DESCRIPTION
**Pull request by frouene**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/6141

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [ ] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [ ] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [ ] Have the relevant issues been added to the pull request?
- [ ] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [ ] Have the relevant issues been added to the same project and milestone as the pull request?
- [ ] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/forms/backend/sirius-components-widget-table/src/main/java/org/eclipse/sirius/components/widget/table/TableWidgetComponent.java [hunk 1]
```diff
@@ -53,6 +54,9 @@ public Element render() {
         List<String> iconURL = tableWidgetDescription.getIconURLProvider().apply(variableManager);
         Boolean readOnly = tableWidgetDescription.getIsReadOnlyProvider().apply(variableManager);
 
+        // In the case of a form, the table ID should not be the representation ID
+        variableManager.put(GetOrCreateRandomIdProvider.PREVIOUS_REPRESENTATION_ID, id);
```
Comment (sbegaudeau) [inline packages/forms/backend/sirius-components-widget-table/src/main/java/org/eclipse/sirius/components/widget/table/TableWidgetComponent.java:58]: Could you explain why that is enough to fix the issue? I can understand that it does but I'm not entirely sure why

Comment (frouene) [reply packages/forms/backend/sirius-components-widget-table/src/main/java/org/eclipse/sirius/components/widget/table/TableWidgetComponent.java:58]: The problem was that when there are several tables in the same form, they all share the same ID. Therefore, during an `IEditCellInput`, the table found is always the first one.
The ID of a table is found with the `PREVIOUS_REPRESENTATION_ID` variable, which is fine for a table in representation mode but not in form mode, since in this case the ID will be the one of the representation form for all tables.
By adding this line, I ensure that each table has a unique ID.

Comment (sbegaudeau) [reply packages/forms/backend/sirius-components-widget-table/src/main/java/org/eclipse/sirius/components/widget/table/TableWidgetComponent.java:58]: Ok so you are overriding the value of `PREVIOUS_REPRESENTATION_ID` which had the id of the form? If that's the case, this is the detail I was missing.

Comment (frouene) [reply packages/forms/backend/sirius-components-widget-table/src/main/java/org/eclipse/sirius/components/widget/table/TableWidgetComponent.java:58]: Yes, exactly

**Review by sbegaudeau — APPROVED** [review]
I'll rebase and merge it
