### PR TITLE
[6220] Prevent keyboard shortcuts from being ignored in diagrams

### LINKED ISSUE #6220: Browser keyboard shortcuts don't work when a diagram has the focus
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
- latest
* [x] **I have specified my environment** : 
- my computer: Windows

### Steps to reproduce

Open a diagram, click on the background of the diagram (or any node/edge), press `Ctrl+h`.

### Expected behavior

The history tab is opened.

### Actual behavior

Nothing happens.

This is most likely related to `useDiagramDirectEdit` and `useDiagramDelete` which are a bit generous on when they call `event.preventDefault()`.

### PR DESCRIPTION
**Pull request by gdaniel**
Bug: https://github.com/eclipse-sirius/sirius-web/issues/6220
Fixes #6220

# Pull request template

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?
_Please describe here the various use cases to test this pull request_

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/useDiagramDirectEdit.tsx [hunk 1]
```diff
@@ -66,8 +65,10 @@ export const useDiagramDirectEdit = (): UseDiagramDirectEditValue => {
       }
       if (currentlyEditedLabelId && isLabelEditable) {
         if (validFirstInputChar) {
+          event.preventDefault();
```
Comment (gdaniel) [inline packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/useDiagramDirectEdit.tsx:68]: This does not prevent default behavior while typing in the direct editing textfield.
For example: pressing F2 on a node, typing a few letters, then hitting `Ctrl + h` will display the history

**Comment by sbegaudeau** [comment]
Quick automatic review (please ignore this message)

  Pull Request Status:
  PR: #6221 (https://github.com/eclipse-sirius/sirius-web/pull/6221) - [6220] Prevent keyboard shortcuts from being ignored in diagrams
  CI Status: Pass (Build, Metadata Review, eclipsefdn/eca)
  Size: Manageable - (6 additions, 4 deletions across 3 files)
  Recommendation: Ready for a thorough review!


  Summary:
  This pull request addresses a bug where standard keyboard shortcuts (like Ctrl+C, Ctrl+V) were being ignored when the focus was on a diagram. The contributor successfully corrected this by moving the event.preventDefault() calls from being unconditional at the beginning of keyboard event handlers to being conditional upon the specific action (deletion or direct edit) actually being triggered. This ensures that unhandled key events can propagate naturally, allowing standard browser and OS shortcuts to function correctly.

  <details>
  <summary>🚨 Critical & Architectural Issues</summary>


  While the functional fix for the bug is correct, the implementation introduces several stale closure risks by violating the Effect Dependencies rule from the react-frontend-reviewer skill.


   1. Missing dependencies in `useDiagramDelete.tsx`:
      In the onDelete callback, multiple variables from the surrounding context are used but not included in the useCallback dependency array. This can lead to the handler using stale context data if the diagram or editing context changes.


    1     // packages/diagrams/frontend/sirius-components-diagrams/src/renderer/delete/useDiagramDelete.tsx
    2     const onDelete = useCallback(
    3       (event: React.KeyboardEvent<Element>) => {
    4         // ...
    5         if (key === 'Delete' && editingContextId && diagramId && !readOnly) {
    6           // ...
    7           const nodeToDeleteIds: string[] = getNodes() // getNodes is missing
    8             .filter((node) => node.selected && node.data.deletable)
    9             .map((node) => node.id);
   10           // ...
   11         }
   12       },
   13       [deleteDiagramElements] // SHOULD INCLUDE: getNodes, getEdges, showDeletionConfirmation, editingContextId, diagramId, readOnly
   14     );


   2. Missing dependencies in `useDiagramDirectEdit.tsx`:
      Similarly, onDirectEdit relies on stale values of getNodes, getEdges, and readOnly.


   1     // packages/diagrams/frontend/sirius-components-diagrams/src/renderer/direct-edit/useDiagramDirectEdit.tsx
   2     const onDirectEdit = useCallback(
   3       (event: React.KeyboardEvent<Element>) => {
   4         // ... uses getNodes(), getEdges(), readOnly
   5       },
   6       [setCurrentlyEditedLabelId] // SHOULD INCLUDE: getNodes, getEdges, readOnly
   7     );


   3. Stale handler in `DiagramRenderer.tsx`:
      The onKeyDown handler in the main renderer is defined with an empty dependency array, meaning it will permanently capture the version of onDirectEdit and onDelete from the very first render. Since these handlers are recreated on every render (due to the issues above and the fact that useDelete does not memoize its return), the diagram will eventually fail to respond correctly to context changes.


   1     // packages/diagrams/frontend/sirius-components-diagrams/src/renderer/DiagramRenderer.tsx
   2     const onKeyDown = useCallback((event: React.KeyboardEvent<Element>) => {
   3       onDirectEdit(event);
   4       onDelete(event);
   5     }, []); // SHOULD INCLUDE: [onDirectEdit, onDelete]

  </details>

  <details>
  <summary>⚠️ Standard & Stylistic Feedback</summary>


   - Copyright Updates: Good job updating the copyright headers to 2026 in the modified files.
   - Memoization: In packages/diagrams/frontend/sirius-components-diagrams/src/renderer/tools/useDelete.tsx (noted during research), the deleteDiagramElements function is not wrapped in useCallback. While not strictly required by the rules for that specific file, it causes downstream useCallback hooks (like onDelete) to trigger unnecessary re-renders or require more complex dependency management.

  </details>

  <details>
  <summary>✅ What Went Well</summary>


  The contributor correctly identified the root cause of the keyboard shortcut interference. By surgically moving event.preventDefault(), they fixed the bug with minimal code changes, maintaining the project's performance and avoiding unnecessary complexity. The inclusion of the fix in the CHANGELOG.adoc is also appreciated for maintainability.


  </details>

**Review by sbegaudeau — APPROVED** [review]
