### PR TITLE
[6105] Fix representation opening in library browser

### LINKED ISSUE #6105: Opening a representation in the library browser is broken
* [x] **I have checked that this feature has not yet been suggested by someone else.**

Nothing prevents library publication mechanisms to create representations in the published libraries.
While this is not done in Sirius Web, it can be done in downstream applications (e.g. publishing a diagram along the library's semantic data to help understand the content of the library).

### Expected behavior

The library browser should be able to display these representations.
These representations should be read-only.

### Actual behavior

A blank page is displayed when the user attempts to open a representation (e.g. a diagram).

The issue is located in [DisplayLibraryView](https://github.com/eclipse-sirius/sirius-web/blob/aa67311e06c27cab70b233d04e0306394935ed03/packages/sirius-web/frontend/sirius-web-application/src/views/display-library/DisplayLibraryView.tsx#L62), which doesn't define `initialRepresentationSelected` and `onRepresentationSelected`

### PR DESCRIPTION
**Pull request by gdaniel**
# Pull request template

Fixes #6105

## General purpose
What is the main goal of this pull request?
- [x] Bug fixes
- [ ] New features
- [ ] Documentation
- [ ] Cleanup
- [ ] Tests
- [ ] Build / releng

## Project management
- [x] Has the pull request been added to the relevant project and milestone? (Only if you know that your work is part of a specific iteration such as the current one)
- [x] Have the `priority:` and `pr:` labels been added to the pull request? (In case of doubt, start with the labels `priority: low` and `pr: to review later`)
- [x] Have the relevant issues been added to the pull request?
- [x] Have the relevant labels been added to the issues? (`area:`, `difficulty:`, `type:`)
- [x] Have the relevant issues been added to the same project and milestone as the pull request?
- [x] Has the `CHANGELOG.adoc` been updated to reference the relevant issues?
- [ ] Have the relevant API breaks been described in the `CHANGELOG.adoc`? (Including changes in the GraphQL API)
- [ ] In case of a change with a visual impact, are there any screenshots in the `CHANGELOG.adoc`? For example in `doc/screenshots/2022.5.0-my-new-feature.png`

## Architectural decision records (ADR)
- [ ] Does the title of the commit contributing the ADR start with `[doc]`?
- [ ] Are the ADRs mentioned in the relevant section of the  `CHANGELOG.adoc`?

## Dependencies
- [ ] Are the new / upgraded dependencies mentioned in the relevant section of the `CHANGELOG.adoc`?
- [ ] Are the new dependencies justified in the `CHANGELOG.adoc`?

## Frontend

This section is not relevant if your contribution does not come with changes to the frontend.

### General purpose
- [ ] Is the code properly tested? (Plain old JavaScript tests for business code and tests based on React Testing Library for the components)

### Typing
We need to improve the typing of our code, as such, we require every contribution to come with proper TypeScript typing for both changes contributing new files and those modifying existing files.
Please ensure that the following statements are true for each file created or modified (this may require you to improve code outside of your contribution).

- [ ] Variables have a proper type
- [ ] Functions’ arguments have a proper type
- [ ] Functions’ return type are specified
- Hooks are properly typed:
	- [ ] `useMutation<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useQuery<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useSubscription<DATA_TYPE, VARIABLE_TYPE>(…)`
	- [ ] `useMachine<CONTEXT_TYPE, EVENTS_TYPE>(…)`
	- [ ] `useState<STATE_TYPE>(…)`
- [ ] All components have a proper typing for their props
- [ ] No useless optional chaining with `?.` (if the GraphQL API specifies that a field cannot be `null`, do not treat it has potentially `null` for example)
- [ ] Nullable values have a proper type (for example `let diagram: Diagram | null = null;`)

## Backend

This section is not relevant if your contribution does not come with changes to the backend.

### General purpose
- [ ] Are all the event handlers tested?
- [ ] Are the event processor tested?
- [ ] Is the business code (services) tested?
- [ ] Are diagram layout changes tested?

### Architecture
- [ ] Are data structure classes properly separated from behavioral classes?
- [ ] Are all the relevant fields final?
- [ ] Is any data structure mutable? If so, please write a comment indicating why
- [ ] Are behavioral classes either stateless or side effect free?

### How to test this PR?

Create a studio and publish it.
Open the library corresponding to the domain of the published studio.
The library should contain a domain diagram.

- [ ] Has the Kiwi TCMS test suite been updated with tests for this contribution?

### CODE REVIEW

File: packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/StudioLibraryRepresentationPublicationListener.java [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+    public void onSemanticDataCreatedEvent(final SemanticDataCreatedEvent semanticDataCreatedEvent) {
+        if (semanticDataCreatedEvent.causedBy() instanceof StudioLibrarySemanticDataCreationRequested request
+                && request.causedBy() instanceof PublishLibrariesInput publishLibrariesInput) {
+
+            Optional<AggregateReference<SemanticData, UUID>> optionalSemanticDataId = new UUIDParser().parse(publishLibrariesInput.editingContextId())
+                    .map(AggregateReference::to);
+
+            if (optionalSemanticDataId.isPresent()) {
+
+                SemanticData librarySemanticData = semanticDataCreatedEvent.semanticData();
```
Comment (gdaniel) [inline packages/sirius-web/backend/sirius-web-application/src/main/java/org/eclipse/sirius/web/application/studio/services/library/StudioLibraryRepresentationPublicationListener.java:75]: The code in this method is very similar to the one in `DuplicateRepresentationEventHandler`. 
The main difference here is the target semantic data, which is not the same as the source one.

I didn't want to extract this code in a service, because in general it doesn't make much sense to copy a representation to another semantic data. Here it does because the content of the semantic data are the same, and the `targetObjectId` doesn't change, but it is clearly not the case in general.

**Review by sbegaudeau — APPROVED** [review]
